<?php

namespace Eyegil\SijupriUkom\Enums;

enum ExamTypesMansoskul: string
{
    case INTEGRITAS = "INTEGRITAS";
    case KERJASAMA = "KERJASAMA";
    case KOMUNIKASI = "KOMUNIKASI";
    case ORIENTASI_HASIL = "ORIENTASI_HASIL";
    case PELAYANAN_PUBLIK = "PELAYANAN_PUBLIK";
    case PENGEMBANGAN_DIRI = "PENGEMBANGAN_DIRI";
    case MENGELOLA_PERUBAHAN = "MENGELOLA_PERUBAHAN";
    case PENGAMBILAN_KEPUTUSAN = "PENGAMBILAN_KEPUTUSAN";
    case PEREKAT_BANGSA = "PEREKAT_BANGSA";
}
