INSERT INTO tbl_akp_kategori_pertanyaan(id,created_at,created_by,updated_at,updated_by,kategori,akp_instrumen_id) 
VALUES 
    (1,NOW(),'system',NULL,NULL,'Pengembangan Standar Mutu Produk',1),
    (2,NOW(),'system',NULL,NULL,'Penilaian Mutu',1),
    (3,NOW(),'system',NULL,NULL,'Penerapan dan Pemantauan Standar Mutu Produk',1),
    (4,NOW(),'system',NULL,NULL,'Pengembangan Standar Mutu Produk',2),
    (5,NOW(),'system',NULL,NULL,'Penilaian Mutu',2),
    (6,NOW(),'system',NULL,NULL,'Penerapan dan Pemantauan Standar Mutu Produk',2),
    (7,NOW(),'system',NULL,NULL,'Pengembangan Standar Mutu Produk',3),
    (8,NOW(),'system',NULL,NULL,'Penilaian Mutu',3),
    (9,NOW(),'system',NULL,NULL,'Penerapan dan Pemantauan Standar Mutu Produk',3),
    (10,NOW(),'system',NULL,NULL,'Penyelenggaraan Sistem Informasi Perdagangan',4),
    (11,NOW(),'system',NULL,NULL,'Pengawasan Barang, Jasa, dan Kegiatan Perdagangan',4),
    (12,NOW(),'system',NULL,NULL,'Penataan Jaringan Distribusi Perdagangan',4),
    (13,NOW(),'system',NULL,NULL,'Analisis kelayakan pelaku usaha, barang, jasa, dan kegiatan perdagangan',4),
    (14,NOW(),'system',NULL,NULL,'Pengumpulan Bahan Keterangan',4),
    (15,NOW(),'system',NULL,NULL,'Penyusunan Kebijakan Bidang Perdagangan',5),
    (16,NOW(),'system',NULL,NULL,'Penyelenggaraan Sistem Informasi Perdagangan',5),
    (17,NOW(),'system',NULL,NULL,'Pengawasan Barang, Jasa dan Kegiatan Perdagangan',5),
    (18,NOW(),'system',NULL,NULL,'Penataan Jaringan Distribusi Perdagangan',5),
    (19,NOW(),'system',NULL,NULL,'Analisis Kelayakan Pelaku-pelaku Usaha, Barang, Jasa, dan Kegiatan Perdagangan',5),
    (20,NOW(),'system',NULL,NULL,'Pengumpulan Bahan Keterangan Tindakan Pidana Pengawasan Barang, Jasa, dan Kegiatan Perdagangan',5),
    (21,NOW(),'system',NULL,NULL,'Penyusunan Kebijakan Bidang Perdagangan',6),
    (22,NOW(),'system',NULL,NULL,'Penyelenggaraan Sistem Informasi Perdagangan',6),
    (23,NOW(),'system',NULL,NULL,'Pengawasan Barang, Jasa dan Kegiatan Perdagangan',6),
    (24,NOW(),'system',NULL,NULL,'Penataan Jaringan Distribusi Perdagangan',6),
    (25,NOW(),'system',NULL,NULL,'Analisis Kelayakan Pelaku Usaha, Barang, Jasa, dan Kegiatan Perdagangan',6),
    (26,NOW(),'system',NULL,NULL,'Pengumpulan bahan Keterangan Tindak Pidana Pengawasan Barang, Jasa dan Kegiatan Perdagangan',6),
    (27,NOW(),'system',NULL,NULL,'PANJANG',7),
    (28,NOW(),'system',NULL,NULL,'PANJANG',7),
    (29,NOW(),'system',NULL,NULL,'PANJANG',7),
    (30,NOW(),'system',NULL,NULL,'VOLUME STATIS',7),
    (31,NOW(),'system',NULL,NULL,'MASSA',7),
    (32,NOW(),'system',NULL,NULL,'MASSA',7),
    (33,NOW(),'system',NULL,NULL,'MASSA',7),
    (34,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',7),
    (35,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',7),
    (36,NOW(),'system',NULL,NULL,'Pengelolaan Instalasi Uji Dalam Rangka Tera dan Tera Ulang',7),
    (37,NOW(),'system',NULL,NULL,'PANJANG',8),
    (38,NOW(),'system',NULL,NULL,'PANJANG',8),
    (39,NOW(),'system',NULL,NULL,'PANJANG',8),
    (40,NOW(),'system',NULL,NULL,'PANJANG',8),
    (41,NOW(),'system',NULL,NULL,'VOLUME STATIS',8),
    (42,NOW(),'system',NULL,NULL,'VOLUME STATIS',8),
    (43,NOW(),'system',NULL,NULL,'VOLUME STATIS',8),
    (44,NOW(),'system',NULL,NULL,'VOLUME STATIS',8),
    (45,NOW(),'system',NULL,NULL,'MASSA',8),
    (46,NOW(),'system',NULL,NULL,'MASSA',8),
    (47,NOW(),'system',NULL,NULL,'MASSA',8),
    (48,NOW(),'system',NULL,NULL,'MASSA',8),
    (49,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',8),
    (50,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',8),
    (51,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',8),
    (52,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',8),
    (53,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',8),
    (54,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',8),
    (55,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',8),
    (56,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',8),
    (57,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',8),
    (58,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',8),
    (59,NOW(),'system',NULL,NULL,'LISTRIK',8),
    (60,NOW(),'system',NULL,NULL,'LISTRIK',8),
    (61,NOW(),'system',NULL,NULL,'Pengelolaan Instalasi Uji Dalam Rangka Tera dan Tera Ulang',8),
    (62,NOW(),'system',NULL,NULL,'PANJANG',9),
    (63,NOW(),'system',NULL,NULL,'PANJANG',9),
    (64,NOW(),'system',NULL,NULL,'PANJANG',9),
    (65,NOW(),'system',NULL,NULL,'PANJANG',9),
    (66,NOW(),'system',NULL,NULL,'PANJANG',9),
    (67,NOW(),'system',NULL,NULL,'PANJANG',9),
    (68,NOW(),'system',NULL,NULL,'PANJANG',9),
    (69,NOW(),'system',NULL,NULL,'VOLUME STATIS',9),
    (70,NOW(),'system',NULL,NULL,'VOLUME STATIS',9),
    (71,NOW(),'system',NULL,NULL,'VOLUME STATIS',9),
    (72,NOW(),'system',NULL,NULL,'VOLUME STATIS',9),
    (73,NOW(),'system',NULL,NULL,'VOLUME STATIS',9),
    (74,NOW(),'system',NULL,NULL,'MASSA',9),
    (75,NOW(),'system',NULL,NULL,'MASSA',9),
    (76,NOW(),'system',NULL,NULL,'MASSA',9),
    (77,NOW(),'system',NULL,NULL,'MASSA',9),
    (78,NOW(),'system',NULL,NULL,'MASSA',9),
    (79,NOW(),'system',NULL,NULL,'MASSA',9),
    (80,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',9),
    (81,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',9),
    (82,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',9),
    (83,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',9),
    (84,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',9),
    (85,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',9),
    (86,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',9),
    (87,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',9),
    (88,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',9),
    (89,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',9),
    (90,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',9),
    (91,NOW(),'system',NULL,NULL,'VOLUME DINAMIS',9),
    (92,NOW(),'system',NULL,NULL,'LISTRIK',9),
    (93,NOW(),'system',NULL,NULL,'LISTRIK',9),
    (94,NOW(),'system',NULL,NULL,'Pengelolaan Instalasi Uji Dalam Rangka Tera dan Tera Ulang',9),
    (95,NOW(),'system',NULL,NULL,'Pemeriksaan Perdagangan Berjangka Komoditi, Sistem Resi Gudang, dan Pasar Lelang Komoditas',10),
    (96,NOW(),'system',NULL,NULL,'Pengaturan Perdagangan Berjangka Komoditi, Sistem Resi Gudang, Pasar Lelang Komoditas',10),
    (97,NOW(),'system',NULL,NULL,'Pembinaan dan Pengembangan Perdagangan Berjangka Komoditi, Sistem Resi Gudang, Pasar Lelang Komoditas',10),
    (98,NOW(),'system',NULL,NULL,'Fasilitasi Substansi Perdagangan Berjangka Komoditi, Sistem Resi Gudang, Pasar Lelang Komoditas',10),
    (99,NOW(),'system',NULL,NULL,'Pemeriksaan Perdagangan Berjangka Komoditi, Sistem Resi Gudang, dan Pasar Lelang Komoditas',11),
    (100,NOW(),'system',NULL,NULL,'Pengaturan Perdagangan Berjangka Komoditi, Sistem Resi Gudang, Pasar Lelang Komoditas',11),
    (101,NOW(),'system',NULL,NULL,'Pembinaan dan Pengembangan Perdagangan Berjangka Komoditi, Sistem Resi Gudang, Pasar Lelang Komoditas',11),
    (102,NOW(),'system',NULL,NULL,'Fasilitasi Substansi Perdagangan Berjangka Komoditi, Sistem Resi Gudang, Pasar Lelang Komoditas',11),
    (103,NOW(),'system',NULL,NULL,'Pemeriksaan Perdagangan Berjangka Komoditi, Sistem Resi Gudang, dan Pasar Lelang Komoditas',12),
    (104,NOW(),'system',NULL,NULL,'Pengaturan Perdagangan Berjangka Komoditi, Sistem Resi Gudang, Pasar Lelang Komoditas',12),
    (105,NOW(),'system',NULL,NULL,'Pembinaan dan Pengembangan Perdagangan Berjangka Komoditi, Sistem Resi Gudang, Pasar Lelang Komoditas',12),
    (106,NOW(),'system',NULL,NULL,'Fasilitasi Substansi Perdagangan Berjangka Komoditi, Sistem Resi Gudang, Pasar Lelang Komoditas',12),
    (107,NOW(),'system',NULL,NULL,'Penyelenggaraan Sistem Informasi Perdagangan',13),
    (108,NOW(),'system',NULL,NULL,'Kerja sama Perdagangan Internasional',13),
    (109,NOW(),'system',NULL,NULL,'Advokasi Kebijakan Bidang Perdagangan',13),
    (110,NOW(),'system',NULL,NULL,'Perundingan di Bidang Perdagangan',13),
    (111,NOW(),'system',NULL,NULL,'Penguasaan Substansi bidang perdagangan di kawasan atau negara mitra',13),
    (112,NOW(),'system',NULL,NULL,'Pelaksanaan Aktivasi Hasil Perundingan Perjanjian Perdagangan Internasional',13),
    (113,NOW(),'system',NULL,NULL,'Penyelenggaraan Sistem Informasi Perdagangan',14),
    (114,NOW(),'system',NULL,NULL,'Kerja sama Perdagangan Internasional',14),
    (115,NOW(),'system',NULL,NULL,'Advokasi Kebijakan Bidang Perdagangan',14),
    (116,NOW(),'system',NULL,NULL,'Perundingan di Bidang Perdagangan',14),
    (117,NOW(),'system',NULL,NULL,'Penguasaan Substansi bidang perdagangan di kawasan atau negara mitra',14),
    (118,NOW(),'system',NULL,NULL,'Pelaksanaan Aktivasi Hasil Perundingan Perjanjian Perdagangan Internasional',14),
    (119,NOW(),'system',NULL,NULL,'Penyelenggaraan Sistem Informasi Perdagangan',15),
    (120,NOW(),'system',NULL,NULL,'Kerja sama Perdagangan Internasional',15),
    (121,NOW(),'system',NULL,NULL,'Advokasi Kebijakan Bidang Perdagangan',15),
    (122,NOW(),'system',NULL,NULL,'Perundingan di Bidang Perdagangan',15),
    (123,NOW(),'system',NULL,NULL,'Penguasaan Substansi bidang perdagangan di kawasan atau negara mitra',15),
    (124,NOW(),'system',NULL,NULL,'Pelaksanaan Aktivasi Hasil Perundingan Perjanjian Perdagangan Internasional',15),
    (125,NOW(),'system',NULL,NULL,'Pengelolaan Ekspor dan Impor',16),
    (126,NOW(),'system',NULL,NULL,'Analisis Kelayakan Penerbitan Dokumen Perizinan/Non Perizinan Bidang Perdagangan',16),
    (127,NOW(),'system',NULL,NULL,'Pengendalian Harga dan Pengelolaan Distribusi',16),
    (128,NOW(),'system',NULL,NULL,'Pemberdayaan Konsumen dan Pembinaan Pelaku Usaha',16),
    (129,NOW(),'system',NULL,NULL,'Penyelenggaraan Promosi Perdagangan',16),
    (130,NOW(),'system',NULL,NULL,'Penyelenggaraan Sistem Informasi Perdagangan',16),
    (131,NOW(),'system',NULL,NULL,'Pengelolaan Ekspor dan Impor',17),
    (132,NOW(),'system',NULL,NULL,'Analisis Kelayakan Penerbitan Dokumen Perizinan/Non Perizinan Bidang Perdagangan',17),
    (133,NOW(),'system',NULL,NULL,'Pengendalian Harga dan Pengelolaan Distribusi',17),
    (134,NOW(),'system',NULL,NULL,'Pemberdayaan Konsumen dan Pembinaan Pelaku Usaha',17),
    (135,NOW(),'system',NULL,NULL,'Penyelenggaraan Promosi Perdagangan',17),
    (136,NOW(),'system',NULL,NULL,'Penyelenggaraan Sistem Informasi Perdagangan',17),
    (137,NOW(),'system',NULL,NULL,'Pengelolaan Ekspor dan Impor',18),
    (138,NOW(),'system',NULL,NULL,'Analisis Kelayakan Penerbitan Dokumen Perizinan/Non Perizinan Bidang Perdagangan',18),
    (139,NOW(),'system',NULL,NULL,'Pengendalian Harga dan Pengelolaan Distribusi',18),
    (140,NOW(),'system',NULL,NULL,'Pemberdayaan Konsumen dan Pembinaan Pelaku Usaha',18),
    (141,NOW(),'system',NULL,NULL,'Penyelenggaraan Promosi Perdagangan',18),
    (142,NOW(),'system',NULL,NULL,'Penyelidikan Tindakan Dumping, Subsidi, dan Tindakan Pengamanan',19),
    (143,NOW(),'system',NULL,NULL,'Penanganan Masalah Hambatan Perdagangan',19),
    (144,NOW(),'system',NULL,NULL,'Penanganan Sengketa Kebijkan Perdagangan Internasional',19),
    (145,NOW(),'system',NULL,NULL,'Penguasaan substansi bidang perdagangan di kawasan atau negara mitra dagang',19),
    (146,NOW(),'system',NULL,NULL,'Pendampingan Hukum dalam Perjanjian Perdagangan Internasional',19),
    (147,NOW(),'system',NULL,NULL,'Advokasi Kebijakan Bidang Perdagangan',19),
    (148,NOW(),'system',NULL,NULL,'Penyelidikan Tindakan Dumping, Subsidi, dan Tindakan Pengamanan',20),
    (149,NOW(),'system',NULL,NULL,'Penanganan Masalah Hambatan Perdagangan',20),
    (150,NOW(),'system',NULL,NULL,'Penanganan Sengketa Kebijkan Perdagangan Internasional',20),
    (151,NOW(),'system',NULL,NULL,'Penguasaan substansi bidang perdagangan di kawasan atau negara mitra dagang',20),
    (152,NOW(),'system',NULL,NULL,'Pendampingan Hukum dalam Perjanjian Perdagangan Internasional',20),
    (153,NOW(),'system',NULL,NULL,'Advokasi Kebijakan Bidang Perdagangan',20),
    (154,NOW(),'system',NULL,NULL,'Penyelidikan Tindakan Dumping, Subsidi, dan Tindakan Pengamanan',21),
    (155,NOW(),'system',NULL,NULL,'Penanganan Masalah Hambatan Perdagangan',21),
    (156,NOW(),'system',NULL,NULL,'Penanganan Sengketa Kebijkan Perdagangan Internasional',21),
    (157,NOW(),'system',NULL,NULL,'Penguasaan substansi bidang perdagangan di kawasan atau negara mitra dagang',21),
    (158,NOW(),'system',NULL,NULL,'Pendampingan Hukum dalam Perjanjian Perdagangan Internasional',21),
    (159,NOW(),'system',NULL,NULL,'Advokasi Kebijakan Bidang Perdagangan',21);