<?php

namespace Database\Seeders\AKP;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AkpPelatihanSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tbl_akp_pelatihan')->insert([
            [ // 1
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Analis Data dan Informasi Produk Ekspor',
                'description' => 'Analis Data dan Informasi Produk Ekspor',
                'jabatan_code' =>  'analis_perdagangan',
            ],
            [ // 2
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kebijakan Ekspor dan Impor',
                'description' => 'Kebijakan Ekspor dan Impor',
                'jabatan_code' =>  'analis_perdagangan',
            ],
            [ // 3
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Market Intellligence',
                'description' => 'Market Intellligence',
                'jabatan_code' =>  'analis_perdagangan',
            ],
            [ // 4
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Analisa Pasar, Produk ekspor, Strategi Pengembangan Serta Promosi Ekspor',
                'description' => 'Analisa Pasar, Produk ekspor, Strategi Pengembangan Serta Promosi Ekspor',
                'jabatan_code' =>  'analis_perdagangan',
            ],
            [ // 5
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengendalian Harga dan Pendistribusian Barang Kebutuhan Pokok',
                'description' => 'Pengendalian Harga dan Pendistribusian Barang Kebutuhan Pokok',
                'jabatan_code' =>  'analis_perdagangan',
            ],
            [ // 6
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pelatihan Edukasi Pemberdayaan dan Perlindungan Konsumen',
                'description' => 'Pelatihan Edukasi Pemberdayaan dan Perlindungan Konsumen',
                'jabatan_code' =>  'analis_perdagangan',
            ],
            [ // 7
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pelatihan Warehouse, Logistic and Distribution Management',
                'description' => 'Pelatihan Warehouse, Logistic and Distribution Management',
                'jabatan_code' =>  'analis_perdagangan',
            ],
            [ // 8
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Negosiation Skills',
                'description' => 'Negosiation Skills',
                'jabatan_code' => 'negosiator_perdagangan',
            ],
            [ // 9
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Penyusunan Pedoman Delri, Naskah State Of Play, Naskah Butir Wicara, Naskah Kertas Posisi Runding, Naskah Briefing Notes, Naskah Fact Sheet, Legal Drafting',
                'description' => 'Penyusunan Pedoman Delri, Naskah State Of Play, Naskah Butir Wicara, Naskah Kertas Posisi Runding, Naskah Briefing Notes, Naskah Fact Sheet, Legal Drafting',
                'jabatan_code' => 'negosiator_perdagangan',
            ],
            [ // 10
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengetahuan GATT, WTO, GATS, NTMs dan Domestic Regulation',
                'description' => 'Pengetahuan GATT, WTO, GATS, NTMs dan Domestic Regulation',
                'jabatan_code' => 'negosiator_perdagangan',
            ],
            [ // 11
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Perundingan',
                'description' => 'Perundingan',
                'jabatan_code' => 'negosiator_perdagangan',
            ],
            [ // 12
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Teknis Request dan Offer Process Transposisi HS Code',
                'description' => 'Teknis Request dan Offer Process Transposisi HS Code',
                'jabatan_code' => 'negosiator_perdagangan',
            ],
            [ // 13
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pelatihan Pemantauan Mutu',
                'description' => 'Pelatihan Pemantauan Mutu',
                'jabatan_code' => 'penjamin_mutu_produk',
            ],
            [ // 14
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pemahaman Standar Nasional Indonesia (SNI)',
                'description' => 'Pemahaman Standar Nasional Indonesia (SNI)',
                'jabatan_code' => 'penjamin_mutu_produk',
            ],
            [ // 15
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pendampingan dan Audir SNI Pasar Rakyat',
                'description' => 'Pendampingan dan Audir SNI Pasar Rakyat',
                'jabatan_code' => 'penjamin_mutu_produk',
            ],
            [ // 16
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengawasan Barang dan Jasa',
                'description' => 'Pengawasan Barang dan Jasa',
                'jabatan_code' => 'pengawas_perdagangan',
            ],
            [ // 17
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengawasan Kegiatan Perdagangan',
                'description' => 'Pengawasan Kegiatan Perdagangan',
                'jabatan_code' => 'pengawas_perdagangan',
            ],
            [ // 18
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengawasn Perdagangan Melalui Sistem elektronik',
                'description' => 'Pengawasn Perdagangan Melalui Sistem elektronik',
                'jabatan_code' => 'pengawas_perdagangan',
            ],
            [ // 19
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengawasan Post Border',
                'description' => 'Pengawasan Post Border',
                'jabatan_code' => 'pengawas_perdagangan',
            ],
            [ // 20
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengawasan Kegiatan Perdaganan ',
                'description' => 'Pengawasan Kegiatan Perdaganan ',
                'jabatan_code' => 'pengawas_perdagangan',
            ],
            [ // 21
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengenalan Komoditi/ Produk Knowledge',
                'description' => 'Pengenalan Komoditi/ Produk Knowledge',
                'jabatan_code' => 'pengawas_perdagangan',
            ],
            [ // 22
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Penyusunan Submisi Pembelaan Tuduhan Trade Reemedies (Dumping, Subsidi, Safeguard) dan Public Hearing',
                'description' => 'Penyusunan Submisi Pembelaan Tuduhan Trade Reemedies (Dumping, Subsidi, Safeguard) dan Public Hearing',
                'jabatan_code' => 'analis_investigasi_dan_pengamanan_perdagangan',
            ],
            [ // 23
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pemberian Asistensi dan Penyusunan Kuesioner Penyelidikan',
                'description' => 'Pemberian Asistensi dan Penyusunan Kuesioner Penyelidikan',
                'jabatan_code' => 'analis_investigasi_dan_pengamanan_perdagangan',
            ],
            [ // 24
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pelatihan Penyelidikan Tindakan Dumping, Subsidi dan Safe Guard',
                'description' => 'Pelatihan Penyelidikan Tindakan Dumping, Subsidi dan Safe Guard',
                'jabatan_code' => 'analis_investigasi_dan_pengamanan_perdagangan',
            ],
            [ // 25
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Data Security, Pengenalan Block Chain, Kemanan data Transaksi',
                'description' => 'Data Security, Pengenalan Block Chain, Kemanan data Transaksi',
                'jabatan_code' => 'pemeriksa_perdagangan_berjangka_komoditi',
            ],
            [ // 26
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pemeriksaan',
                'description' => 'Pemeriksaan',
                'jabatan_code' => 'pemeriksa_perdagangan_berjangka_komoditi',
            ],
            [ // 27
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Forensic and (in) Cyber Security',
                'description' => 'Forensic and (in) Cyber Security',
                'jabatan_code' => 'pemeriksa_perdagangan_berjangka_komoditi',
            ],
            [ // 28
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Verifikasi Jangka Sorong',
                'description' => 'Verifikasi Jangka Sorong',
                'jabatan_code' => 'penera',
            ],
            [ // 29
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Verifikasi Komparator Sidang',
                'description' => 'Verifikasi Komparator Sidang',
                'jabatan_code' => 'penera',
            ],
            [ // 30
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Verifikasi Timbangan Jembatan',
                'description' => 'Verifikasi Timbangan Jembatan',
                'jabatan_code' => 'penera',
            ],
            [ // 31
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Verifikasi Meter Gas Industri dan Rumah Tangga',
                'description' => 'Verifikasi Meter Gas Industri dan Rumah Tangga',
                'jabatan_code' => 'penera',
            ],
            [ // 32
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Verifikasi Sphygmomanometer',
                'description' => 'Verifikasi Sphygmomanometer',
                'jabatan_code' => 'penera',
            ],
            [ // 33
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Meter Kadar Air',
                'description' => 'Kalibrasi/Verifikasi Meter Kadar Air',
                'jabatan_code' => 'penera',
            ],
            [ // 34
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Pressure Recorder dan Temperature Recorder',
                'description' => 'Kalibrasi/Verifikasi Pressure Recorder dan Temperature Recorder',
                'jabatan_code' => 'penera',
            ],
            [ // 35
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Temperatur Non-Kontak (Termometer Infrared)',
                'description' => 'Kalibrasi/Verifikasi Temperatur Non-Kontak (Termometer Infrared)',
                'jabatan_code' => 'penera',
            ],
            [ // 36
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Thermohygrometer',
                'description' => 'Kalibrasi/Verifikasi Thermohygrometer',
                'jabatan_code' => 'penera',
            ],
            [ // 37
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Dead Weight Tester (DWT)',
                'description' => 'Kalibrasi/Verifikasi Dead Weight Tester (DWT)',
                'jabatan_code' => 'penera',
            ],
            [ // 38
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Climatic Chamber',
                'description' => 'Kalibrasi/Verifikasi Climatic Chamber',
                'jabatan_code' => 'penera',
            ],
            [ // 39
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Enclosure',
                'description' => 'Kalibrasi/Verifikasi Enclosure',
                'jabatan_code' => 'penera',
            ],
            [ // 40
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Glassware',
                'description' => 'Kalibrasi/Verifikasi Glassware',
                'jabatan_code' => 'penera',
            ],
            [ // 41
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Hydrometer dengan Metode Chuckow',
                'description' => 'Kalibrasi/Verifikasi Hydrometer dengan Metode Chuckow',
                'jabatan_code' => 'penera',
            ],
            [ // 42
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Multimeter',
                'description' => 'Kalibrasi/Verifikasi Multimeter',
                'jabatan_code' => 'penera',
            ],
            [ // 43
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Stopwatch',
                'description' => 'Kalibrasi/Verifikasi Stopwatch',
                'jabatan_code' => 'penera',
            ],
            [ // 44
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Alat Ukur Frekuensi',
                'description' => 'Kalibrasi/Verifikasi Alat Ukur Frekuensi',
                'jabatan_code' => 'penera',
            ],
            [ // 45
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Kalibrasi/Verifikasi Flowmeter',
                'description' => 'Kalibrasi/Verifikasi Flowmeter',
                'jabatan_code' => 'penera',
            ],
            [ // 46
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Teknis Reparasi Timbangan Pasar (Timbangan Meja, Pegas, Dacin Logam, dan Sentisimal)',
                'description' => 'Teknis Reparasi Timbangan Pasar (Timbangan Meja, Pegas, Dacin Logam, dan Sentisimal)',
                'jabatan_code' => 'penera',
            ],
            [ // 47
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Timbangan Elektronik',
                'description' => 'Peneraan Timbangan Elektronik',
                'jabatan_code' => 'penera',
            ],
            [ // 48
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Timbangan Jembatan',
                'description' => 'Peneraan Timbangan Jembatan',
                'jabatan_code' => 'penera',
            ],
            [ // 49
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Tangki Ukur Mobil Bahan Bakar Minyak',
                'description' => 'Peneraan Tangki Ukur Mobil Bahan Bakar Minyak',
                'jabatan_code' => 'penera',
            ],
            [ // 50
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Meter Air',
                'description' => 'Peneraan Meter Air',
                'jabatan_code' => 'penera',
            ],
            [ // 51
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Meter Kadar Air',
                'description' => 'Peneraan Meter Kadar Air',
                'jabatan_code' => 'penera',
            ],
            [ // 52
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Meter kWh',
                'description' => 'Peneraan Meter kWh',
                'jabatan_code' => 'penera',
            ],
            [ // 53
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Meter Gas Diaphragma',
                'description' => 'Peneraan Meter Gas Diaphragma',
                'jabatan_code' => 'penera',
            ],
            [ // 54
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Tangki Ukur Tetap Silinder Tegak Bahan Bakar Minyak',
                'description' => 'Peneraan Tangki Ukur Tetap Silinder Tegak Bahan Bakar Minyak',
                'jabatan_code' => 'penera',
            ],
            [ // 55
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Timbangan Pengecek dan Penyortir',
                'description' => 'Peneraan Timbangan Pengecek dan Penyortir',
                'jabatan_code' => 'penera',
            ],
            [ // 56
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Timbangan Ban Berjalan',
                'description' => 'Peneraan Timbangan Ban Berjalan',
                'jabatan_code' => 'penera',
            ],
            [ // 57
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Meter Arus BBM/Flowmeter',
                'description' => 'Peneraan Meter Arus BBM/Flowmeter',
                'jabatan_code' => 'penera',
            ],
            [ // 58
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Pompa Ukur BBM',
                'description' => 'Peneraan Pompa Ukur BBM',
                'jabatan_code' => 'penera',
            ],
            [ // 59
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Peneraan Timbangan Bukan Otomatis',
                'description' => 'Peneraan Timbangan Bukan Otomatis',
                'jabatan_code' => 'penera',
            ],
            [ // 60
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Penggunaan Teodolite dalam pengujian Tangki Ukur Silinder Tegak',
                'description' => 'Penggunaan Teodolite dalam pengujian Tangki Ukur Silinder Tegak',
                'jabatan_code' => 'penera',
            ],
            [ // 61
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengujian Meter Gas Orifice dan Transmitter-Transmitternya (Pressure, Differential Pressure, Temperature, dan Three Pens Recorder)',
                'description' => 'Pengujian Meter Gas Orifice dan Transmitter-Transmitternya (Pressure, Differential Pressure, Temperature, dan Three Pens Recorder)',
                'jabatan_code' => 'penera',
            ],
            [ // 62
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengujian Ultra Sonic Meter dan Transmitter-Transmitternya (Pressure dan Temperature)',
                'description' => 'Pengujian Ultra Sonic Meter dan Transmitter-Transmitternya (Pressure dan Temperature)',
                'jabatan_code' => 'penera',
            ],
            [ // 63
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'PenggunaanTotal Station dalam Pengujian Tangki Ukur Tetap Silinder Tegak',
                'description' => 'PenggunaanTotal Station dalam Pengujian Tangki Ukur Tetap Silinder Tegak',
                'jabatan_code' => 'penera',
            ],
            [ // 64
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Penggunaan dan Pelatihan EMC (ESD, Voltage Dip, Surge, EFT yang diterapkan untuk NAWI-Elektronik) dengan Peralatan Standar berikut: ESD Generator (NSG 435); Compact NX Generator (Compact NX5); Motorized Variac; High Speed Coupling/Decoupling (CNI 508N2), RF Generator (NSG 407C-35); Capacitive Coupling Clamp; EM Clamp (KEMZ 801A).',
                'description' => 'Penggunaan dan Pelatihan EMC (ESD, Voltage Dip, Surge, EFT yang diterapkan untuk NAWI-Elektronik) dengan Peralatan Standar berikut: ESD Generator (NSG 435); Compact NX Generator (Compact NX5); Motorized Variac; High Speed Coupling/Decoupling (CNI 508N2), RF Generator (NSG 407C-35); Capacitive Coupling Clamp; EM Clamp (KEMZ 801A).',
                'jabatan_code' => 'penera',
            ],
            [ // 65
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengoperasian dan Pemrograman CMM untuk Pengujian',
                'description' => 'Pengoperasian dan Pemrograman CMM untuk Pengujian',
                'jabatan_code' => 'penera',
            ],
            [ // 66
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengujian Automatic Level Gauge (Radar, Servo, Capacitance, Electromagnetic, dll)',
                'description' => 'Pengujian Automatic Level Gauge (Radar, Servo, Capacitance, Electromagnetic, dll)',
                'jabatan_code' => 'penera',
            ],
            [ // 67
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengujian Transmitter (Pressure, Differential Pressure, dan Temperature)',
                'description' => 'Pengujian Transmitter (Pressure, Differential Pressure, dan Temperature)',
                'jabatan_code' => 'penera',
            ],
            [ // 68
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengenalan dan Penerapan Sistem K3L di Instalasi Uji',
                'description' => 'Pengenalan dan Penerapan Sistem K3L di Instalasi Uji',
                'jabatan_code' => 'penera',
            ],
            [ // 69
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengenalan dan Pengujian Sistem Meter Arus BBM dan Massflow Meter',
                'description' => 'Pengenalan dan Pengujian Sistem Meter Arus BBM dan Massflow Meter',
                'jabatan_code' => 'penera',
            ],
            [ // 70
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengujian ATG/ATC',
                'description' => 'Pengujian ATG/ATC',
                'jabatan_code' => 'penera',
            ],
            [ // 71
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pemahaman Interkomparasi, Cek Antara dan Interpersonel, serta Penerapannya',
                'description' => 'Pemahaman Interkomparasi, Cek Antara dan Interpersonel, serta Penerapannya',
                'jabatan_code' => 'penera',
            ],
            [ // 72
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Penggunaan Software Kelton Calculation dan ABB Flow-Xpert untuk Pengujian Sistem MGO, USM, Meter Gas Turbin, dll.',
                'description' => 'Penggunaan Software Kelton Calculation dan ABB Flow-Xpert untuk Pengujian Sistem MGO, USM, Meter Gas Turbin, dll.',
                'jabatan_code' => 'penera',
            ],
            [ // 73
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pelatihan “Customer Satisfaction”',
                'description' => 'Pelatihan “Customer Satisfaction”',
                'jabatan_code' => 'penera',
            ],
            [ // 74
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Manajemen Pemeliharaan Test Bench dan Perlengkapannya',
                'description' => 'Manajemen Pemeliharaan Test Bench dan Perlengkapannya',
                'jabatan_code' => 'penera',
            ],
            [ // 75
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Analisis Perhitungan Nilai Ketidakpastian Pengujian Meter Arus BBM',
                'description' => 'Analisis Perhitungan Nilai Ketidakpastian Pengujian Meter Arus BBM',
                'jabatan_code' => 'penera',
            ],
            [ // 76
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Manajemen Pengelolaan Lab. Pengujian Flowmeter Non-Air Menurut ISO 17025',
                'description' => 'Manajemen Pengelolaan Lab. Pengujian Flowmeter Non-Air Menurut ISO 17025',
                'jabatan_code' => 'penera',
            ],
            [ // 77
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Aplikasi Pengolahan Data Statistik Pengolahan Data Ekspesimen dan Hasil Pengujian',
                'description' => 'Aplikasi Pengolahan Data Statistik Pengolahan Data Ekspesimen dan Hasil Pengujian',
                'jabatan_code' => 'penera',
            ],
            [ // 78
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pengujian Pompa Ukur Elpiji Menurut ST 121 Tahun 2020',
                'description' => 'Pengujian Pompa Ukur Elpiji Menurut ST 121 Tahun 2020',
                'jabatan_code' => 'penera',
            ],
            [ // 79
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'Pelatihan DUPAK Jabatan Fungsional Penera',
                'description' => 'Pelatihan DUPAK Jabatan Fungsional Penera',
                'jabatan_code' => 'penera',
            ],
            [ // 80
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'BDKT Jumlah Hitung Luas Panjang ',
                'description' => 'BDKT Jumlah Hitung Luas Panjang ',
                'jabatan_code' => 'pengawas_kemetrologian',
            ],
            [ // 81
                'created_at' => now(),
                'created_by' => 'system',
                'name' => 'BDKT Frozen dan Drainweight ',
                'description' => 'BDKT Frozen dan Drainweight ',
                'jabatan_code' => 'pengawas_kemetrologian',
            ],
        ]);
    }
}
