INSERT INTO tbl_akp_pertanyaan(id,created_at,created_by,updated_at,updated_by,pertanyaan,akp_kategori_pertanyaan_id) 
VALUES 
    (NOW(),'system',NULL,NULL,'Mampu menganalisis data dan informasi terkait pengembangan standar mutu produk.',1),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis data dan informasi potensi kerjasama terkait mutu.',1),
    (NOW(),'system',NULL,NULL,'Mampu menginventarisir data dan informasi dalam rangka menyusun materi kerja sama terkait mutu dalam forum internasional.',1),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi isu rencana kerjasama terkait mutu.',1),
    (NOW(),'system',NULL,NULL,'Mampu mengolah biografi data importir atau komoditi dalam rangka penerapan standar mutu produk.',2),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemeriksaan kelengkapan dokumen ketertelusuran terkait penilaian mutu.',2),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi data dan informasi mutu produk.',2),
    (NOW(),'system',NULL,NULL,'Mampu melakukan analisis data dan informasi terkait penilaian kinerja kelembagaan terkait mutu.',2),
    (NOW(),'system',NULL,NULL,'Mampu melaksanakan pemantauan mutu produk.',2),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi kebutuhan penerapan sistem terkait mutu.',3),
    (NOW(),'system',NULL,NULL,'Mampu melaksanakan audit sistem terkait mutu dalam rangka pengelolaan sistem mutu.',3),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis data dan informasi pemberlakukan standar mutu produk.',3),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemeriksaan dan rekapitulasi kelengkapan dokumen sebagai pemenuhan persyaratan penerapan sistem terkait mutu.',3),
    (NOW(),'system',NULL,NULL,'Mampu menyusun perencanaan pelaksanaan pemantauan mutu produk.',3),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis standar mutu produk yang akan dikembangkan.',4),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemetaan terhadap risiko penerapan pengembangan standar mutu produk.',4),
    (NOW(),'system',NULL,NULL,'Mampu menyusun ruang lingkup kerjasama terkait mutu dan menyusun tanggapan teknis terkait mutu untuk kerjasama lingkup nasional.',4),
    (NOW(),'system',NULL,NULL,'Mampu menentukan isu-isu yang mempengaruhi pengembangan standar mutu produk.',4),
    (NOW(),'system',NULL,NULL,'Mampu',4),
    (NOW(),'system',NULL,NULL,'Mampu melakukan validasi dokumen dalam rangka kaji ulang standar mutu produk yang telah diterapkan.',5),
    (NOW(),'system',NULL,NULL,'Mampu menyusun kuesioner penilaian kinerja kelembagaan terkait mutu, program uji profisiensi, dan pemantauan mutu produk.',5),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis data dan informasi terkait penilaian sistem mutu yang menjadi kewenangannya.',5),
    (NOW(),'system',NULL,NULL,'Mampu memverifikasi kesesuaian kualitas sumber daya manusia dengan ketentuan di bidang standardisasi dan',5),
    (NOW(),'system',NULL,NULL,'pengendalian mutu.',5),
    (NOW(),'system',NULL,NULL,'Mampu melakukan penyaksian audit dalam rangka penilaian kinerja kelembagaan terkait mutu.',5),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis pemenuhan persyaratan penerapan sistem terkait mutu.',6),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis hasil kaji ulang dan audit penerapan sistem terkait mutu.',6),
    (NOW(),'system',NULL,NULL,'Mampu melakukan validasi dokumen/analyzing point dalam rangka ketertelusuran terkait mutu.',6),
    (NOW(),'system',NULL,NULL,'Mampu melakukan tinjauan terhadap hasil audit dan penerapan sistem terkait mutu.',6),
    (NOW(),'system',NULL,NULL,'Mampu menyusun dan mengevaluasi standar mutu produk dan program pengembangannya.',7),
    (NOW(),'system',NULL,NULL,'Mampu melakukan analisis biaya manfaat dari tawaran kerjasama dan evaluasi kerja sama terkait mutu.',7),
    (NOW(),'system',NULL,NULL,'Mampu melakukan uji kesesuaian standar dengan ilmu pengetahuan dan teknologi.',7),
    (NOW(),'system',NULL,NULL,'Mampu melakukan verifikasi usulan pengembangan standar.',7),
    (NOW(),'system',NULL,NULL,'Mampu menyusun tanggapan teknis terkait mutu dalam forum internasional.',7),
    (NOW(),'system',NULL,NULL,'Mampu melakukan penilaian hasil analyzing point penerapan standar mutu produk, dan kinerja kelembagaan terkait mutu.',8),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pengujian kualitas SDM dan klarifikasi informasi temuan ketidaksesuaian kinerja kelembagaan terkait mutu.',8),
    (NOW(),'system',NULL,NULL,'Mampu melakukan evaluasi pelaksanaan uji profisiensi atau uji banding laboratorium, hasil pemetaan importir atau komoditi penerapan standar mutu produk, dan pelaksanaan kebijakan standar mutu produk.',8),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis efektifitas pemberlakukan standar mutu produk.',8),
    (NOW(),'system',NULL,NULL,'Mampu menyusun rencana pendampingan penerapan standar terkait mutu.',8),
    (NOW(),'system',NULL,NULL,'Mampu mengevaluasi kesesuaian persyaratan penerapan sistem terkait mutu.',9),
    (NOW(),'system',NULL,NULL,'Mampu memverifikasi hasil audit sistem terkait mutu.',9),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis susunan tim audit sistem terkait mutu berdasarkan kompetensi.',9),
    (NOW(),'system',NULL,NULL,'Mampu menyusun perencanaan program audit sistem terkait mutu.',9),
    (NOW(),'system',NULL,NULL,'Mampu melakukan evaluasi dan rekomendasi standar mutu produk.',9),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis dan memverifikasi data dan informasi perdagangan yang menjadi kewenangannya dan memberikan masukan dalam rangka perbaikan.',10),
    (NOW(),'system',NULL,NULL,'Mampu menyusun database bidang perdagangan yang menjadi kewenangannya.',10),
    (NOW(),'system',NULL,NULL,'Mampu menentukan format/tampilan penyajian data dan informasi yang akan ditampilkan di website.',10),
    (NOW(),'system',NULL,NULL,'Mampu memberikan informasi yang relevan kepada masyarakat dan stakeholder tentang data dan informasi perdagangan yang menjadi kewenangannya.',10),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemeriksaan kebenaran legalitas informasi.',11),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemeriksaan terhadap kesesuaian perizinan dengan aktivitas kegiatan.',11),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemeriksaan terhadap kesesuaian SNI, persyaratan teknis, atau kualifikasi yang diberlakukan secara wajib.',11),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemeriksaan terhadap asal barang dan data lain yang diperlukan.',11),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis dan memverifikasi data dan informasi terkait jaringan distribusi, sarana distribusi perdagangan dan logistik meliputi proposal pembangunan sarana distribusi perdagangan, meliputi usulan lokasi, tipe dan pembiayaan sarana distribusi perdagangan.',12),
    (NOW(),'system',NULL,NULL,'Mampu melakukan verifikasi bahan dan laporan hasil pemantauan dan kegiatan pengelolaan sarana distribusi perdagangan di daerah sesuai dengan prosedur.',12),
    (NOW(),'system',NULL,NULL,'Mampu menjelaskan konsep dasar terkait jaringan distribusi, sarana distribusi perdagangan dan logistik.',12),
    (NOW(),'system',NULL,NULL,'Mampu melakukan analisis terhadap data dan informasi yang didapat dari pengamatan kasat mata/pemeriksaan legalitas.',13),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis hasil pengambilan sampel untuk melihat kelayakan barang atau jasa.',13),
    (NOW(),'system',NULL,NULL,'Mampu menyajikan hasil analisis dan menjelaskan secara lengkap, rinci, dan jelas terhadap hasil analisis kelayakan pelaku usaha, barang, jasa, dan kegiatan perdagangan.',13),
    (NOW(),'system',NULL,NULL,'Mampu menyusun laporan hasil pelaku usaha, barang, jasa, dan kegiatan perdagangan.',13),
    (NOW(),'system',NULL,NULL,'Mampu memahami konsep dasar dan metode/teknik melakukan identifikasi dan pengumpulan data dan informasi.',14),
    (NOW(),'system',NULL,NULL,'Mampu memahami dan mampu menjelaskan proses dalam deteksi dan identifikasi data dan informasi dalam rangka pulbaket.',14),
    (NOW(),'system',NULL,NULL,'Mampu menyiapkan konsep surat-surat dan dokumen pendukung kegiatan pengumpulan bahan keterangan.',14),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan penilaian dan evalusasi terhadap naskah suatu kebijakan, mengidentifikasi kekurangan dan merumuskan perbaikan terhadap naskah kebijakan.',15),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan penilaian dan evalusasi implementasi kebijakan, menguasai konten dan konteks kebijakan, mengetahui dampak positif dan negatif dari suatu kebijakan, mengetahui hambatan dan daya dukung terhadap implementasi kebijakan, serta dapat melakukan koordinasi dengan stakeholders dalam implementasi kebijakan.',15),
    (NOW(),'system',NULL,NULL,'Kemampuan menyusun perencanaan dan melaksanakan program monitoring dan evaluasi terhadap penerapan suatu kebijakan, serta melakukan analisis terhadap hasil monitoring dan evaluasi.',15),
    (NOW(),'system',NULL,NULL,'Kemampuan menganalisis dan memverifikasi data dan informasi perdagangan yang menjadi kewenangannya dan memberikan masukan dalam rangka perbaikan.',16),
    (NOW(),'system',NULL,NULL,'Kemampuan menentukan format/tampilan penyajian data dan informasi yang akan ditampilkan di website.',16),
    (NOW(),'system',NULL,NULL,'Kemampuan memberikan informasi yang relevan kepada masyarakat dan stakeholders tentang data dan informasi perdagangan yang menjadi kewenenangannya.',16),
    (NOW(),'system',NULL,NULL,'Kemampuan membuat perencanaan pengawasan.',17),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan pemetaan target pengawasan.',17),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan pemeriksaan kesesuaian legalitas dan kegiatan usaha.',17),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan pemeriksaan terhadap kesesuaian standar nasional indonesia, persyaratan teknis, atau kualifikasi yang diberlakukan secara wajib.',17),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan koordinasi dengan kementerian/lembaga terkait.',17),
    (NOW(),'system',NULL,NULL,'Kemampuan mengidentifikasi permasalahan terkait hasil pengawasan.',17),
    (NOW(),'system',NULL,NULL,'Kemampuan menyusun perencanaan berdasarkan hasil identifikasi jaringan distribusi, sarana distribusi perdagangan, dan logistik.',18),
    (NOW(),'system',NULL,NULL,'Kemampuan memberikan rekomendasi terkait jaringan distribusi, sarana distribusi perdagangan, dan logistik.',18),
    (NOW(),'system',NULL,NULL,'Kemampuan mengkoordinir pelaksanaan monitoring terhadap implementasi kebijakan jaringan distribusi, sarana distribusi perdagangan dan logistik.',18),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukanj koordinasi dengan pemangku kepentingan untuk membahas permasalahan terkait perumusan kebijakan dan implementasi penataan jaringan distribusi, sarana distribusi perdagangan dan logistik.',18),
    (NOW(),'system',NULL,NULL,'Kemampuan mengidentifikasi kebutuhan terkait jaringan distribusi, sarana distribusi perdagangan dan logistik.',18),
    (NOW(),'system',NULL,NULL,'Kemampuan menentukan data dan informasi yang dapat ditindaklanjuti untuk dianalisis kelayakannya.',19),
    (NOW(),'system',NULL,NULL,'Kemampuan menganalisis hasil pemeriksaan kesesuaian antara instrumen hukum dengan realita di lapangan.',19),
    (NOW(),'system',NULL,NULL,'Kemampuan mengoordinir penetapan tindak lanjut hasil analisis kelayakan, seperti tindakan pengamanan atau pengumpulan bahan keterangan tindak pidana.',19),
    (NOW(),'system',NULL,NULL,'Kemampuan mensosialisasikan  kebijakan dan memberikan bimbingan, coaching, mentoring, kepada pihak-pihak terkait dalam melakukan pelaku usaha, barang, jasa, dan kegiatan perdagangan.',19),
    (NOW(),'system',NULL,NULL,'Kemampuan memecahkan masalah teknis  operasional yang timbul dan mengambil keputusan dalam melakukan pelaku usaha, barang, jasa, dan kegiatan perdagangan.',19),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan analisis terhadap data dan informasi yang didapat dari hasil pengawasan.',20),
    (NOW(),'system',NULL,NULL,'Kemampuan mengidentifikasi data dan informasi yang dibutuhkan dalam pengumpulan bahan keterangan tindak pidana pengawasan barang, jasa dan kegiatan perdagangan.',20),
    (NOW(),'system',NULL,NULL,'Kemampuan menyusun data base hasil pengawasan kegiatan perdagangan,  pengawasan barang dan pengawasan jasa yang akan ditindaklanjuti.  menjelaskan secara lengkap, rinci, dan jelas terhadap hasil analisis kelayakan pelaku usaha, barang, jasa, dan kegiatan perdagangan.',20),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan penyelarasan (harmonisasi) substansi dengan peraturan perundang-undangan yang lain, mampu merumuskan intisari dari suatu kebijakan yang akan memberikan dampak positf dari maksud dan tujuan kebijakan bagi instansi dan masyarakat serta mampu menetapkan untuk menjadi draf/naskah final suatu kebijakan.',21),
    (NOW(),'system',NULL,NULL,'Kemampuan menguasai kunci-kunci sukses dalam implementasi suatu kebijakan, dan menerapkan praktek terbaik pendekatan implementasi kebijakan, mampu merumuskan solusi terhadap hambatan dalam implementasi suatu kebijakan dan mengembangkan pendekatan baru dalam implementasi, dan mampu memberikan dorongan dan mengambil keputusan untuk meningkatkan efektivitas implementasi suatu kebijakan.',21),
    (NOW(),'system',NULL,NULL,'Kemampuan menguasai praktek terbaik pendekatan monitoring dan evaluasi kebijakan di negara benchmark; menetapkan upaya perbaikan dan menetapkan langkah-langkah tindak lanjut dari hasil monitoring dan evaluasi, merumuskan perbaikan terhadap kebijakan.',21),
    (NOW(),'system',NULL,NULL,'Kemampuan menyusun rencana dan melaksanakan program monitoring terhadap implementasi pengelolaan sistem informasi perdagangan yang menjadi kewenangannya.',22),
    (NOW(),'system',NULL,NULL,'Kemampuan mengidentifikasi kekurangan dan merumuskan perbaikan terhadap implementasi pengelolaan sistem informasi perdagangan yang menjadi kewenangannya.',22),
    (NOW(),'system',NULL,NULL,'Kemampuan meberikan bimbingan dan fasilitasi kepada instansi lain atau stakeholder terkait dalam menerapkan sistem informasi perdagangan.',22),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan klarifikasi di bidang pengawasan kegiatan perdagangan/pengawasan barang beredar dan/atau jasa.',23),
    (NOW(),'system',NULL,NULL,'Kemampuan menyampaikan laporan hasil pengawasan kegiatan perdagangan /pengawasan barang beredar dan/atau jasa sebagai dasar tindak lanjut ke tahap penyidikan.',23),
    (NOW(),'system',NULL,NULL,'Kemampuan mengevaluasi pengawasan kegiatan perdagangan, pengawasan barang dan pengawasan jasa.',23),
    (NOW(),'system',NULL,NULL,'Kemampuan menyusun rencana pendidikan.',23),
    (NOW(),'system',NULL,NULL,'Kemampuan memetakan kekuatan sumber daya dalam rangka kelancaran pelaksanaan penyidikan.',23),
    (NOW(),'system',NULL,NULL,'Kemampuan mengatasi dan memfasilitasi konflik pada saat pelaksanaan pengawasan.',23),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan kegiatan pengamanan barang bukti.',23),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan pengolahan tempat kejadian perkara.',23),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan penyitaan barang bukti.',23),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan pemeriksaan terhadap saksi dan/atau tersangka, dan/atau ahli.',23),
    (NOW(),'system',NULL,NULL,'Kemampuan menyusun berkas perkara.',23),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan gelar perkara.',23),
    (NOW(),'system',NULL,NULL,'Kemampuan menentukan metode pelaksanaan evaluasi implementasi kebijakan penataan jaringan distribusi, sarana distribusi perdagangan dan logistik.',24),
    (NOW(),'system',NULL,NULL,'Kemampuan mengembangkan jaringan distribusi, sarana distribusi perdagangan dan logistik sesuai ketentuan.',24),
    (NOW(),'system',NULL,NULL,'Kemampuan memastikan pelayanan terkait jaringan distribusi, sarana distribusi perdagangan dan logistik dilaksanakan sesuai prosedur dan mampu memastikan terselenggaranya pelaksanaan kegiatan jaringan distribusi, sarana distribusi pedagangan, dan logistik.',24),
    (NOW(),'system',NULL,NULL,'Kemampuan menyiapkan langkah-langkah antisipasi dari isu-isu yang berkembang di bidang jaringan distribusi, sarana distribusi perdagangan, dan logistik.',24),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan evaluasi terhadap teknik/metode/sistem cara kerja, melakukan pengembangan atau perbaikan cara kerja penyusunan pelaku usaha, barang, jasa, dan kegiatan perdagangan.',25),
    (NOW(),'system',NULL,NULL,'Kemampuan menyusun pedoman, petunjuk teknis, cara kerja yang dijadikan norma, standar, prosedur, instrumen pelaksanaan pelaku usaha, barang, jasa dan kegiatan perdagangan.',25),
    (NOW(),'system',NULL,NULL,'Kemampuan merancang atau membuat instrumen untuk melakukan pelaku usaha, barang, jasa dan kegiatan perdagangan; melakukan permintaan informasi dan/atau klarifikasi terhadap hasil pelaku usaha, barang, jasa, dan kegiatan perdagangan.',25),
    (NOW(),'system',NULL,NULL,'Kemampuan menentukan data dan informasi yang diperlukan dalam kegiatan pengumpulan bahan keterangan tindak pidana pengawasan barang, jasa dan kegiatan perdagangan.',26),
    (NOW(),'system',NULL,NULL,'Kemampuan melaksanakan kegiatan surveillance, penggalangan dan undercover untuk memperoleh data yang dapat disajikan sebagai sumber informasi.',26),
    (NOW(),'system',NULL,NULL,'Kemampuan mengkoordinir pelaksanaan pengumpulan bahan keterangan tindak pidana pengawasan barang, jasa dan kegiatan perdagangan serta informasi yang relevan.',26),
    (NOW(),'system',NULL,NULL,'Kemampuan memecahkan masalah teknis operasional dalam pelaksanaan pengumpulan bahan keterangan tindak pidana pengawasan barang, jasa dan kegiatan perdagangan.',26),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian UTTP besaran panjang',27),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan  Pengujian UTTP besaran panjang',27),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap UTTP besaran panjang',27),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian UTTP Jenis Meter Taksi',28),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian UTTP Jenis Meter Taksi',28),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap UTTP Jenis Meter Taksi',28),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian UTTP Jenis Meter Parkir',29),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian UTTP Jenis Meter Parkir',29),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap UTTP Jenis Meter Parkir',29),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Takaran',30),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian takaran',30),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan  terhadap takaran',30),
    (NOW(),'system',NULL,NULL,'Melakukan persiapan pengujian Timbangan Bukan Otomatis',31),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Timbangan bukan otomatis',31),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap timbangan bukan otomatis',31),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Timbangan Meja Beranger',32),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Timbangan Meja Beranger',32),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Timbangan Meja Beranger',32),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Kadar Air',33),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Meter Kadar Air',33),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan  terhadap Meter Kadar Air',33),
    (NOW(),'system',NULL,NULL,'Melakukan persiapan pengujian pompa ukur BBM',34),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Pompa Ukur BBM',34),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Pompa Ukur BBM',34),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian',35),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Meter Air Dingin',35),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Air Dingin',35),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi peralatan instalasi uji dan fungsinya;',36),
    (NOW(),'system',NULL,NULL,'Mampu memahami prosedur pengelolaan instalasi uji',36),
    (NOW(),'system',NULL,NULL,'Mampu memahami penanganan peralatan instalasi uji',36),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Ullage Temperature Interface (UTI)',37),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan  Pengujian Ullage Temperature Interface (UTI)',37),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Ullage Temperature Interface (UTI)',37),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Automatic Level Gauge',38),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Automatic Level Gauge',38),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Automatic Level Gauge',38),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Float Level Gauge',39),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Float Level Gauge',39),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Float Level Gauge',39),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Electromagnetic Level Gauge',40),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Electromagnetic Level Gauge',40),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Electromagnetic Level Gauge',40),
    (NOW(),'system',NULL,NULL,'Melakukan persiapan pengujian Tangki Ukur Mobil.',41),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Tangki Ukur Mobil',41),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Tangki Ukur Mobil',41),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Tangki Ukur Tetap Silinder Tegak.',42),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Tangki Ukur Tetap Silinder Tegak',42),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan  terhadap Tangki Ukur Tetap Silinder Tegak',42),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Tangki Ukur Tongkang.',43),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Tangki Ukur Tongkang',43),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan  terhadap Tangki Ukur Tongkang',43),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Tangki Ukur Kapal',44),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Tangki Ukur Kapal',44),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan  terhadap Tangki Ukur Kapal',44),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Timbangan Ban Berjalan',45),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Timbangan Ban Berjalan',45),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Timbangan Ban Berjalan',45),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Weighing in Motion (Timbangan Kendaraan Bergerak)',46),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Weighing in Motion (Timbangan Kendaraan Bergerak)',46),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Weighing in Motion (Timbangan Kendaraan Bergerak)',46),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Railweight Bridge (Timbangan Kereta Api Bergerak)',47),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Railweight Bridge (Timbangan Kereta Api Bergerak)',47),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Railweight Bridge (Timbangan Kereta Api Bergerak)',47),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Kadar Air',48),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Meter Kadar Air',48),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan  terhadap Meter Kadar Air',48),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Pompa ukur Elpiji',49),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Pompa ukur Elpiji',49),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Pompa ukur Elpiji',49),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Pompa ukur BBG',50),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Pompa ukur BBG',50),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Pompa ukur BBG',50),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Arus BBM',51),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Meter Arus BBM',51),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Arus BBM',51),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Gas Volumetric dan Inferensial',52),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Meter Gas Volumetric dan Inferensial',52),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Gas Volumetric dan Inferensial',52),
    (NOW(),'system',NULL,NULL,'Memeriksa kelengkapan administrasi UTTP Besaran Arus, Jenis Meter Gas Diafragma',53),
    (NOW(),'system',NULL,NULL,'Merencanakan dan mempersiapkan pengujian',53),
    (NOW(),'system',NULL,NULL,'Melakukan pengujian',53),
    (NOW(),'system',NULL,NULL,'Mengakhiri pengujian',53),
    (NOW(),'system',NULL,NULL,'Membuat laporan hasil pengujian',53),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Gas Basah',54),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Meter Gas Basah',54),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Gas Basah',54),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Gas Orifice',55),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Meter Gas Orifice',55),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Gas Orifice',55),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Gas Vortex',56),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Meter Gas Vortex',56),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Gas Vortex',56),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Gas Mass Flowmeter',57),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Gas Mass Flowmeter',57),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Gas Mass Flowmeter',57),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Gas Ultrasonic',58),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Meter Gas Ultrasonic',58),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Gas Ultrasonic',58),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian',59),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Meter kWh',59),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter kWh',59),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter kWh kelas 0,2 atau (D)',60),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Meter kWh kelas 0,2 atau (D)',60),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter kWh kelas 0,2 atau (D)',60),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi peralatan instalasi uji yang perlu diperbaiki',61),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pengelolaan instalasi uji sesuai dengan prosedur',61),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemantauan kondisi dan/atau akomodasi  lingkungan sesuai dengan persyaratan yang ditetapkan oleh instalasi uji.',61),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian UTTP besaran panjang',62),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan  Pengujian UTTP besaran panjang',62),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap UTTP besaran panjang',62),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Ullage Temperature Interface (UTI)',63),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan  Pengujian Ullage Temperature Interface (UTI)',63),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Ullage Temperature Interface (UTI)',63),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Automatic Level Gauge',64),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Automatic Level Gauge',64),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Automatic Level Gauge',64),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Float Level Gauge',65),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Float Level Gauge',65),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Float Level Gauge',65),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Electromagnetic Level Gauge',66),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Electromagnetic Level Gauge',66),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Electromagnetic Level Gauge',66),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian UTTP Jenis Meter Taksi',67),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian UTTP Jenis Meter Taksi',67),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap UTTP Jenis Meter Taksi',67),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian UTTP Jenis Meter Parkir',68),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian UTTP Jenis Meter Parkir',68),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap UTTP Jenis Meter Parkir',68),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Takaran',69),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian takaran',69),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan  terhadap takaran',69),
    (NOW(),'system',NULL,NULL,'Melakukan persiapan pengujian Tangki Ukur Mobil.',70),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Tangki Ukur Mobil',70),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Tangki Ukur Mobil',70),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Tangki Ukur Tetap Silinder Tegak.',71),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Tangki Ukur Tetap Silinder Tegak',71),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan  terhadap Tangki Ukur Tetap Silinder Tegak',71),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Tangki Ukur Tongkang.',72),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Tangki Ukur Tongkang',72),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan  terhadap Tangki Ukur Tongkang',72),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Tangki Ukur Kapal',73),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Tangki Ukur Kapal',73),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan  terhadap Tangki Ukur Kapal',73),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Timbangan Ban Berjalan',74),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Timbangan Ban Berjalan',74),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Timbangan Ban Berjalan',74),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Weighing in Motion (Timbangan Kendaraan Bergerak)',75),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Weighing in Motion (Timbangan Kendaraan Bergerak)',75),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Weighing in Motion (Timbangan Kendaraan Bergerak)',75),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Railweight Bridge (Timbangan Kereta Api Bergerak)',76),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Railweight Bridge (Timbangan Kereta Api Bergerak)',76),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Railweight Bridge (Timbangan Kereta Api Bergerak)',76),
    (NOW(),'system',NULL,NULL,'Melakukan persiapan pengujian Timbangan Bukan Otomatis',77),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Timbangan bukan otomatis',77),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap timbangan bukan otomatis',77),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Timbangan Meja Beranger',78),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Timbangan Meja Beranger',78),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Timbangan Meja Beranger',78),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Kadar Air',79),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Meter Kadar Air',79),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan  terhadap Meter Kadar Air',79),
    (NOW(),'system',NULL,NULL,'Melakukan persiapan pengujian pompa ukur BBM',80),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Pompa Ukur BBM',80),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Pompa Ukur BBM',80),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Pompa ukur Elpiji',81),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Pompa ukur Elpiji',81),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Pompa ukur Elpiji',81),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Pompa ukur BBG',82),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Pompa ukur BBG',82),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Pompa ukur BBG',82),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Arus BBM',83),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Meter Arus BBM',83),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Arus BBM',83),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Gas Volumetric dan Inferensial',84),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Meter Gas Volumetric dan Inferensial',84),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Gas Volumetric dan Inferensial',84),
    (NOW(),'system',NULL,NULL,'Memeriksa kelengkapan administrasi UTTP Besaran Arus, Jenis Meter Gas Diafragma',85),
    (NOW(),'system',NULL,NULL,'Merencanakan dan mempersiapkan pengujian',85),
    (NOW(),'system',NULL,NULL,'Melakukan pengujian',85),
    (NOW(),'system',NULL,NULL,'Mengakhiri pengujian',85),
    (NOW(),'system',NULL,NULL,'Membuat laporan hasil pengujian',85),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Gas Basah',86),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Meter Gas Basah',86),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Gas Basah',86),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Gas Orifice',87),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Meter Gas Orifice',87),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Gas Orifice',87),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Gas Vortex',88),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Meter Gas Vortex',88),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Gas Vortex',88),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Gas Mass Flowmeter',89),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Gas Mass Flowmeter',89),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Gas Mass Flowmeter',89),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter Gas Ultrasonic',90),
    (NOW(),'system',NULL,NULL,'Melakukan Pemeriksaan dan Pengujian Meter Gas Ultrasonic',90),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Gas Ultrasonic',90),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian',91),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Meter Air Dingin',91),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter Air Dingin',91),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian',92),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Meter kWh',92),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter kWh',92),
    (NOW(),'system',NULL,NULL,'Melakukan Persiapan Pengujian Meter kWh kelas 0,2 atau (D)',93),
    (NOW(),'system',NULL,NULL,'Melakukan Pengujian Meter kWh kelas 0,2 atau (D)',93),
    (NOW(),'system',NULL,NULL,'Memberikan keputusan Sah/Batal terhadap Meter kWh kelas 0,2 atau (D)',93),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi peralatan instalasi uji yang perlu diperbaiki',94),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pengelolaan instalasi uji sesuai dengan prosedur',94),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemantauan kondisi dan/atau akomodasi  lingkungan sesuai dengan persyaratan yang ditetapkan oleh instalasi uji.',94),
    (NOW(),'system',NULL,NULL,'Mampu menerima dan melakukan penanganan laporan dan/atau pengaduan di bidang perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',95),
    (NOW(),'system',NULL,NULL,'Mampu menyusun Kertas Kerja Pemeriksaan/Pengawasan/Audit dan melakukan dokumentasi atas pelaksanaan pemeriksaan/ pengawasan/audit.',95),
    (NOW(),'system',NULL,NULL,'Mampu melakukan konsultasi pelaksanaan pemeriksaan/pengawasan/audit di bidang perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',95),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi kepatuhan penyampaian Laporan Periodik Kelembagaan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',95),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis bahan kajian substansial dan rumusan kebijakan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',96),
    (NOW(),'system',NULL,NULL,'Mampu menyusun dan menyelaraskan kebijakan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',96),
    (NOW(),'system',NULL,NULL,'Mampu memberikan layanan informasi kebijakan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',96),
    (NOW(),'system',NULL,NULL,'Mampu memeriksa Kelengkapan usulan permohonan perizinan dibidang perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',96),
    (NOW(),'system',NULL,NULL,'Mampu menyajikan data dan informasi pembinaan dan pengembangan pelaku usaha.',97),
    (NOW(),'system',NULL,NULL,'Mampu menyusun materi publikasi kegiatan pembinaan dan pengembangan.',97),
    (NOW(),'system',NULL,NULL,'Mampu melakukan identifikasi Potensi wilayah dan sentra produksi untuk pengembangan sistem resi gudang/ pasar lelang komoditas.',97),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis permintaan tanggapan hukum, konsultasi hukum dan penyelesaian perselisihan.',98),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis penanganan perkara hukum gugatan hukum dan bantuan hukum didalam dan luar persidangan serta praperadilan.',98),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis kasus perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',98),
    (NOW(),'system',NULL,NULL,'Mampu melakukan klarifikasi  terhadap hasil pengawasan Kepatuhan Kegiatan Pialang Berjangka dan Pelaporan Direktur Kepatuhan.',99),
    (NOW(),'system',NULL,NULL,'Mampu menyusun rencana kerja, program kerja, rencana kegiatan dalam pemeriksaan/ pengawasan/audit di bidang perdagangan berjangka komoditi/sistem resi gudang/pasar lelang komoditas.',99),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis laporan, pengaduan, petunjuk serta laporan keuangan, kelembagaan perdagangan berjangka komoditi/sistem resi gudang/pasar lelang komoditas.',99),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemetaan dan identifikasi serta observasi terhadap dugaan pelanggaran perdagangan berjangka komoditi/sistem resi gudang/pasar lelang komoditas.',99),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemeriksaan/pengawasan/audit terhadap pihak-pihak yang diduga melakukan pelanggaran serta pemeriksaan teknis kelembagaan secara online dan on-site.',99),
    (NOW(),'system',NULL,NULL,'Mampu melaksanakan kegiatan pemantauan penyaluran subsidi melalui kredit program di bidang sistem resi gudang.',99),
    (NOW(),'system',NULL,NULL,'Mampu mengolah, menganalisis data, menyusun program kerja pengawasan/audit tahunan dan menilai kategori pelaku usaha yang akan diaudit oleh bursa berjangka dan lembaga kliring berjangka serta mereviu hasil audit bursa berjangka dan lembaga kliring berjangka.',99),
    (NOW(),'system',NULL,NULL,'Mampu melaksanakan program monitoring dan evaluasi terhadap penerapan kebijakan terkait perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',100),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi kekurangan dan merumuskan rekomendasi perbaikan terhadap pengaturan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',100),
    (NOW(),'system',NULL,NULL,'Mampu berkoordinasi dengan pemangku kepentingan dalam rangka menyelesaikan permasalahan terkait pengaturan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',100),
    (NOW(),'system',NULL,NULL,'Mampu mengimplementasikan cara yang efektif untuk mengatasi masalah yang dihadapi pada saat pelaksanaan penyelenggaraan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',100),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemeriksaan sarana fisik dalam rangka perizinan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',101),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis data dan informasi pembinaan dan pengembangan kelembagaan dan produk serta pembinaan dan pengembangan pelaku usaha.',101),
    (NOW(),'system',NULL,NULL,'Mampu melakukan monitoring pengembangan kelembagaan dan produk.',101),
    (NOW(),'system',NULL,NULL,'Mampu melakukan konsultasi terhadap kerja sama bidang perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',101),
    (NOW(),'system',NULL,NULL,'Mampu melakukan asistensi di bidang perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',101),
    (NOW(),'system',NULL,NULL,'Mampu membuat perencanaan penanganan perkara di dalam dan di luar persidangan serta pra peradilan.',102),
    (NOW(),'system',NULL,NULL,'Mampu melakukan penanganan perkara di dalam dan di luar persidangan serta pra peradilan.',102),
    (NOW(),'system',NULL,NULL,'Mampu memberi tanggapan atas penyelesaian perselisihan di bidang perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',102),
    (NOW(),'system',NULL,NULL,'Mampu membuat rekomendasi tindak lanjut hasil identifikasi, dan/atau surveilance terhadap dugaan adanya pelanggaran.',103),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis dan membuat rekomendasi atas hasil pemeriksaan/ pengawasan/audit, melakukan evaluasi terhadap pelaksanaan pemeriksaan/pengawasan/audit, dan monitoring atas tindak lanjut hasil pemeriksaan/ pengawasan/audit.',103),
    (NOW(),'system',NULL,NULL,'Mampu merekomendasikan tindak lanjut hasil gelar kasus.',103),
    (NOW(),'system',NULL,NULL,'Mampu mereviu peta risiko daftar pertanyaan kuesioner dan menetapkan usulan draft kuesioner penyusunan program kerja pengawasan/audit tahunan.',103),
    (NOW(),'system',NULL,NULL,'Mampu mereviu daftar usulan pelaku usaha yang akan diaudit oleh Bursa Berjangka dan Lembaga Kliring Berjangka dan menyusun rekomendasi (usulan kebijakan) atas hasil reviu terhadap hasil audit bursa berjangka dan lembaga kliring berjangka.',103),
    (NOW(),'system',NULL,NULL,'Mampu melakukan verifikasi dan memberikan rekomendasi terkait permohonan perizinan di bidang perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',104),
    (NOW(),'system',NULL,NULL,'Mampu melakukan uji kelayakan dan kepatutan dalam rangka perizinan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',104),
    (NOW(),'system',NULL,NULL,'Mampu melakukan penyelarasan program dan kegiatan penerapan kebijakan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',104),
    (NOW(),'system',NULL,NULL,'Mampu merumuskan rekomendasi hasil penyelarasan kebijakan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',104),
    (NOW(),'system',NULL,NULL,'Mampu menyusun materi kerja sama dan mengkaji ulang implementasi kerja sama bidang perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas di tingkat nasional.',104),
    (NOW(),'system',NULL,NULL,'Mampu melakukan reviu hasil analisis produk dan hasil analisis pengembangan pasar dan kebijakan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',105),
    (NOW(),'system',NULL,NULL,'Mampu merekomendasikan pengembangan produk dan/atau kelembagaan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',105),
    (NOW(),'system',NULL,NULL,'Mampu mendesain perangkat monitoring dan evaluasi kelembagaan dan produk.',105),
    (NOW(),'system',NULL,NULL,'Mampu melakukan evaluasi pelaksanaan pembinaan/ metode/ program pemeriksaan perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',105),
    (NOW(),'system',NULL,NULL,'Mampu mereviu penanganan perkara di dalam dan di luar persidangan serta pra peradilan.',106),
    (NOW(),'system',NULL,NULL,'Mampu merekomendasikan hasil tanggapan atas penyelesaian perselisihan di bidang perdagangan berjangka komoditi/ sistem resi gudang/ pasar lelang komoditas.',106),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis dan memverifikasi data dan informasi perdagangan yang menjadi kewenangannya dan memberikan masukan dalam rangka perbaikan.',107),
    (NOW(),'system',NULL,NULL,'Mampu menentukan format/tampilan penyajian data dan informasi yang akan ditampilkan di website.',107),
    (NOW(),'system',NULL,NULL,'Mampu memberikan informasi yang relevan kepada masyarakat dan  stakeholder tentang data dan informasi perdagangan yang menjadi kewenangannya.',107),
    (NOW(),'system',NULL,NULL,'Mampu melakukan inventarisasi dan identifikasi data dan informasi terkait negara mitra serta isu terkait kerja sama.',108),
    (NOW(),'system',NULL,NULL,'Mampu memverifikasi dan menganalisis data dan informasi yang didapat dari pihak terkait baik eksternal dan internal dalam menyusun bahan kerja sama Perdagangan .Internasional serta memberikan umpan balik dalam rangka perbaikan konsep bahan Kerjasama Perdagangan Internasional.',108),
    (NOW(),'system',NULL,NULL,'Mampu menyajikan data dan informasi terkait penyusunan bahan kerja sama Perdagangan Internasional.',108),
    (NOW(),'system',NULL,NULL,'Mampu melakukan kegiatan yang bersifat operasional terkait pelaksanaan kerja sama perdagangan internasional.',108),
    (NOW(),'system',NULL,NULL,'Mampu menyusun rencana pelaksanaan kegiatan advokasi kebijakan, melalui persuasi, sosialisasi, bimbingan teknis, pendampingan, monitoring evaluasi advokasi kebijakan publik.',109),
    (NOW(),'system',NULL,NULL,'Mampu melakukan sosialisasi kebijakan publik dengan presentasi yang effektif, mengunakan fitur dan alat bantu presentasi, sesuai tipe audiens serta strategi penyampaian pesan yang adekuat kepada para stakeholder sehingga dapat memahami serta menerapkan kebijakan.',109),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi mana kebutuhan meeting, memformulasikan agenda meeting dan mendesain merancang materi dan bahan, alat bantu, rundown meeting serta minutes of meeting yang efektif.',109),
    (NOW(),'system',NULL,NULL,'Mampu memahami teknik teknik negosiasi, antara lain metode mempengaruhi dan mempertahankan posisi dalam suatu perundingan.',110),
    (NOW(),'system',NULL,NULL,'Mampu mengkoordinasikan dan mengkomunikasikan dengan baik dan tepat akan kebutuhan informasi bahan dukung',110),
    (NOW(),'system',NULL,NULL,'perundingan.',110),
    (NOW(),'system',NULL,NULL,'Mampu memverifikasi dan menganalisis data dan informasi yang didapat dari pihak terkait baik eksternal dan internal dalam menyusun posisi runding serta memberikan umpan balik dalam rangka perbaikan konsep posisi runding.',110),
    (NOW(),'system',NULL,NULL,'Mampu memberikan informasi yang relevan jika ada pertanyaan lebih lanjut terkait konsep posisi runding yang disusun.',110),
    (NOW(),'system',NULL,NULL,'Mampu menyajikan data dan informasi terkait penyusunan posisi runding dan penyusunan deklarasi yang menjadi kesepakatan tingkat menteri atau kepala negara.',110),
    (NOW(),'system',NULL,NULL,'Mampu mengklasifikasikan posisi dasar atau kepentingan politik dan hubungan luar negeri terkait substansi bidang perdagangan di kawasan atau negara mitra dagang yang ditangani.',111),
    (NOW(),'system',NULL,NULL,'Mampu memonitor dan menentukan potensi dan tantangan terkait substansi bidang perdagangan di kawasan atau negara mitra dagang yang ditangani terhadap kepentingan ekonomi dan hubungan luar negeri.',111),
    (NOW(),'system',NULL,NULL,'Mampu mengolah data dan informasi menjadi materi untuk ditelaah.',111),
    (NOW(),'system',NULL,NULL,'Mampu menyiapkan bahan penyampaian perjanjian perdagangan internasional berdasarkan hasil perundingan.',112),
    (NOW(),'system',NULL,NULL,'Mampu menyiapkan dokumen pelaksanaan operasional dan aktivasi hasil perundingan perjanjian perdagangan internasional.',112),
    (NOW(),'system',NULL,NULL,'Mampu menyajikan data dan informasi terkait hasil perundingan perjanjian internasional sebagai tindak lanjut hasil perjanjian perdagangan internasional.',112),
    (NOW(),'system',NULL,NULL,'Mampu menyusun materi publikasi hasil perundingan.',112),
    (NOW(),'system',NULL,NULL,'Mampu menyusun rencana dan melaksanakan program monitoring terhadap implementasi Pengelolaan sistem informasi perdagangan yang menjadi kewenangannya.',113),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi kekurangan dan merumuskan perbaikan terhadap implementasi Pengelolaan sistem informasi perdagangan yang menajdi kewenangannya.',113),
    (NOW(),'system',NULL,NULL,'Mampu memberikan bimbingan dan fasilitasi kepada instansi lain atau stakeholder terkait dalam menerapkan Sistem Informasi Perdagangan.',113),
    (NOW(),'system',NULL,NULL,'Mampu menyiapkan bahan kerja sama Perdagangan Internasional/ rancangan kerangka acuan/TOR/concept note/non-paper/ proposal kerja sama/ preliminary study/ rancangan nota kesepahaman/ rancangan dokumen perjanjian perdagangan internasional/riset/kajian.',114),
    (NOW(),'system',NULL,NULL,'Mampu melakukan konsultasi atau verifikasi materi perluasan kerja sama perdagangan internasional dengan instansi terkait.',114),
    (NOW(),'system',NULL,NULL,'Mampu melakukan diseminasi informasi pengembangan kerja sama perdagangan internasional.',114),
    (NOW(),'system',NULL,NULL,'Mampu mengembangkan serta menjalankan strategi atau intervensi dalam mengatasi hambatan sistemik dan resistensi stakeholder dalam menerapkan kebijakan serta mampu mengembangkan serta menjalankan strategi atau intervensi dalam memaksimalkan sumber daya yang dimiliki stakeholder.',115),
    (NOW(),'system',NULL,NULL,'Mampu mengimplementasikan strategi komunikasi dengan target dan waktu yang terukur dan terencana dengan mendapatkan hasil sesuai yang diharapkan.',115),
    (NOW(),'system',NULL,NULL,'Mampu mengantarkan sebuah sesi presentasi yang efektif dan efisien dengan menggunakan alat bantu dan strategi presentasi yang cukup sehingga pesan dapat tersampaikan dengen baik ke audien, mampu mengendalikan diri dalam berurusan dengan kondisi dan audiens yang sulit dan mampu menguasai jalannya sesi presentasi sesuai dengan alokasi materi dan waktu yang telah ditetapkan.',115),
    (NOW(),'system',NULL,NULL,'Mampu mengontrol jalannya meeting dengan efektif dan efisien sesuai dengan sasaran dengan menjalankan strategi yang telah ditetapkan sebelumnya, menggunakan alat bantu yang disediakan serta sesuai dengan run down acara, mampu mengendalikan meeting dalam kondisi yang sulit dan mengatasi peserta rapat yang tidak koordinatif dan mampu mengarahkan dan mencapai kata sepakat antar anggota meeting.',115),
    (NOW(),'system',NULL,NULL,'Mampu menguasai teknik-teknik negosiasi, antara lain metode mempengaruhi dan mempertahankan posisi dalam suatu perundingan.',116),
    (NOW(),'system',NULL,NULL,'Mampu menyusun konsep naskah posisi runding, usulan deklarasi yang menjadi kesepakatan pada tingkat menteri atau kepala negara.',116),
    (NOW(),'system',NULL,NULL,'Mampu menyusun argumen yang disampaikan dalam opsi-opsi rekomendasi posisi runding.',116),
    (NOW(),'system',NULL,NULL,'Mampu menangani konflik/perbedaan pendapat yang terjadi pada saat perundingan dan mengarahkan pihak lain untuk menyetujui posisi runding yang diajukan.',116),
    (NOW(),'system',NULL,NULL,'Mampu menelaah materi dengan mengkorelasikan hubungan sebab-akibat.',117),
    (NOW(),'system',NULL,NULL,'Mampu merumuskan hasil korelasi secara logis dengan mempertimbangkan faktor pro dan kontra serta kekuatan dan kelemahan suatu argumentasi.',117),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis arah dan strategi kebijakan luar negeri Indonesia pada substansi bidang perdagangan di kawasan atau negara mitra dagang yang ditangani.',117),
    (NOW(),'system',NULL,NULL,'Mampu memformulasikan dokumen penyampaian perjanjian perdagangan internasional.',118),
    (NOW(),'system',NULL,NULL,'Mampu menyusun penjelasan ratifikasi perjanjian perdagangan internasional.',118),
    (NOW(),'system',NULL,NULL,'Mampu menyusun bahan terjemahan perjanjian perdagangan internasional dalam rangka ratifikasi perjanjian perdagangan internasional yang telah disepakati.',118),
    (NOW(),'system',NULL,NULL,'Mampu melakukan evaluasi pelaksanaan pengelolaan data dan Informasi Perdagangan yang ada saat ini dalam rangka melakukan atau perbaikan menjadi lebih efektif/efisien.',119),
    (NOW(),'system',NULL,NULL,'Mampu proses bisnis terkait pengelolaan data dan Informasi Perdagangan yang menjadi kewenangannya.',119),
    (NOW(),'system',NULL,NULL,'Mampu memberikan rekomendasi pengelolaan data dan informasi perdagangan yang efektif dengan integrasi data agar informasi yang disajikan tepat dan berdaya guna.',119),
    (NOW(),'system',NULL,NULL,'Mampu melakukan penilaian dan evaluasi terhadap bahan kerja sama perdagangan internasional, mengidentifikasi kekurangan dan merumuskan perbaikan terhadap bahan kerja sama perdagangan internasional.',120),
    (NOW(),'system',NULL,NULL,'Mampu melakukan monitoring dan evaluasi pelaksanaan kerja sama perdagangan internasional untuk mengetahui kelebihan dan kekurangan dalam penyampaian bahan kerja sama perdagangan internasional sebagai dasar perbaikan ke depan.',120),
    (NOW(),'system',NULL,NULL,'Mampu menyusun materi pengembangan kerja sama perdagangan internasional berdasarkan hasil monitoring dan evaluasi.',120),
    (NOW(),'system',NULL,NULL,'Mampu melakukan kegiatan yang bersifat strategis sektoral terkait pelaksanaan kerja sama perdagangan internasional.',120),
    (NOW(),'system',NULL,NULL,'Mampu memberdayakan stakeholder untuk mengembangkan strategi advokasi yang tepat untuk diri mereka sendiri, mengidentifikasi hambatan di lingkungan mereka sendiri dalam penerapan kebijakan serta menemukan akses ke sumber daya yang dibutuhkan untuk menerapkan kebijakan.',121),
    (NOW(),'system',NULL,NULL,'Mampu mengevaluasi strategi komunikasi yang telah dilaksanakan dan menyusun strategi baru yang lebih efektif dalam rangka meningkatkan kualitas komunikasi atau mencapai target-target yang lebih tinggi atau menghadapi situasi yang lebih sulit.',121),
    (NOW(),'system',NULL,NULL,'Mampu mengevaluasi diri sendiri dan orang lain dalam menjalankan suatu sesi presentasi dan menyediakan masukan berdasarkan hasil evaluasi tersebut dan menjadi tutor yang baik dalam membimbing orang lain menguasai teknik presentasi yang efektif dan efisien.',121),
    (NOW(),'system',NULL,NULL,'Mampu untuk mengevaluasi jalannya suatu meeting serta menyusun suatu strategi serta intervensi untuk mengoptimalkan meeting selanjutnya.',121),
    (NOW(),'system',NULL,NULL,'Mampu menguasai teknik teknik negosiasi dan mempraktekkannya dalam mengambil keputusan yang strategis dan menguntungkan sesuai dengan mandat/kepentingan nasional.',122),
    (NOW(),'system',NULL,NULL,'Mampu melakukan penilaian dan evaluasi terhadap bahan posisi runding, mengidentifikasi kekurangan dan merumuskan perbaikan terhadap bahan posisi runding.',122),
    (NOW(),'system',NULL,NULL,'Mampu mengevaluasi pelaksanaan perundingan untuk mengetahui kelebihan dan kekurangan dalam penyampaian posisi runding sebagai dasar perbaikan ke depan.',122),
    (NOW(),'system',NULL,NULL,'Mampu memberikan pertimbangan hubungan sebab akibat yang lebih kompleks dalam merumuskan materi terkait substansi bidang perdagangan di kawasan atau negara mitra dagang yang ditangani.',123),
    (NOW(),'system',NULL,NULL,'Mampu menyertakan dan memperjelas sudut pandang yang berbeda untuk memperkaya hasil análisis.',123),
    (NOW(),'system',NULL,NULL,'Mampu merumuskan hasil observasi, isu dan ide yang kompleks menjadi hasil analisis yang mudah dimengerti.',123),
    (NOW(),'system',NULL,NULL,'Mampu melakukan analisis biaya dan manfaat dalam rangka ratifikasi perjanjian perdagangan internasional.',124),
    (NOW(),'system',NULL,NULL,'Mampu menyusun analisis manfaat dan peluang kedepan terkait ratifikasi perjanjian perdagangan internasional.',124),
    (NOW(),'system',NULL,NULL,'Mampu menyusun notifikasi ke negara mitra runding dan lembaga lembaga perdagangan internasional.',124),
    (NOW(),'system',NULL,NULL,'Mampu melakukan diseminasi dan sosialisasi hasil perjanjian perdagangan internasional kepada pemangku kepentingan.',124),
    (NOW(),'system',NULL,NULL,'Mampu menyusun materi monitoring dan evaluasi pemanfaatan hasil perjanjian perdagangan internasional.',124),
    (NOW(),'system',NULL,NULL,'mampu memahami Kebijakan Tata Niaga Ekspor Non Migas dan Kebijakan pengembangan pasar dan informasi ekspor',125),
    (NOW(),'system',NULL,NULL,'mampu melakukan penghitungan alokasi ekspor dalam rangka penerbitan persetujuan ekspor dan perhitungan alokasi impor dalam rangka penetapan alokasi impor produk tertentu',125),
    (NOW(),'system',NULL,NULL,'mampu melaksanakan komunikasi secara efektif dalam rangka pemberian konsultasi terkait kebijakan ekspor/impor',125),
    (NOW(),'system',NULL,NULL,'mampu mengetahui dan memahami permasalahan teknis perdagangan seperti hambatan tarif dan hambatan non tarif',125),
    (NOW(),'system',NULL,NULL,'mampu menganalisis faktor-faktor yang mempengaruhi kebijakan ekspor dan impor seperti selera konsumen, harga barang, nilai tukar dan biaya logistik',125),
    (NOW(),'system',NULL,NULL,'mampu mengetahui dan mengetahui tata cara pemeriksaan dokumen perijinan Perdagangan',126),
    (NOW(),'system',NULL,NULL,'mampu mengolah data kompleks mengenai penerbitan dokumen perizinan/non perizinan menjadi bahan visualisasi data/infografis',126),
    (NOW(),'system',NULL,NULL,'mampu melaksanakan komunikasi tertulis terkait hasil hasil analisis kelayakan penerbitan dokumen dokumen perizinan/non perizinan bidang perdagangan',126),
    (NOW(),'system',NULL,NULL,'mampu mengoperasikan aplikasi sistem informasi perizinan atau non perizinan bidang perdagangan seperti inatrade',126),
    (NOW(),'system',NULL,NULL,'mampu melakukan pemantauan harga atau stok barang pokok dan barang penting sesuai dengan prosedur yang ditetapkan',127),
    (NOW(),'system',NULL,NULL,'mampu melakukan analisis secara kualitatif dan kuantitatif terkait  hasil Pemantauan Harga dan Pasokan/Stok Barang Kebutuhan Pokok dan Barang Penting',127),
    (NOW(),'system',NULL,NULL,'mampu melakukan analisis data dan informasi terkait jaringan distribusi, sarana perdagangan dan logistik dan potensi, kebutuhan dan perhitungan pembiayaan pembangunan/revitalisasi sarana perdagangan serta analisis pemberdayaan dan peningkatan kualitas pengelolaan pasar rakyat',127),
    (NOW(),'system',NULL,NULL,'mampu melakukan analisis potensi isu dan isu kenaikan/penurunan harga dan stok Barang Kebutuhan Pokok dan Barang Penting dan mampu melakukan analisis kenaikan dan penurunan harga komoditi secara ekstrim yang berdampak kepada inflasi/deflasi',127),
    (NOW(),'system',NULL,NULL,'mampu melakukan verifikasi langsung by sistem (SP2KP dan check & balance pelaku usaha terkait (produsen, distributor, pengecer)',127),
    (NOW(),'system',NULL,NULL,'mampu melakukan analisis data dan informasi serta berkomunikasi secara efektif dalam pelaksanaan kegiatan pemberdayaan konsumen dan pembinaan pelaku usaha',128),
    (NOW(),'system',NULL,NULL,'mampu menyusun (seluruh/sebagian) rencana kegiatan seperti edukasi konsumen/pelaku usaha, layanan konsumen (penganganan pengaduan, konsultasi, dan asistensi), kelembagaan perlindungan konsumen, serta kerjasama perlindungan konsumen di tingkat nasional dan internasional',128),
    (NOW(),'system',NULL,NULL,'mampu berkomunikasi secara efektif dalam memberikan layanan konsultasi dan inforasi di bidang pemberdayaan konsumen dan pembinaan pelaku usaha',128),
    (NOW(),'system',NULL,NULL,'mampu berkomunikasi secara efektif dalam melaksanakan pelayanan pengaduan dan mampu menjadi mediator antara konsumen dengan pelaku usaha',128),
    (NOW(),'system',NULL,NULL,'mampu melakukan pembaharuan data dan penyusunan laporan terkait dengan pemberdayaan konsumen dan pembinaan pelaku usaha',128),
    (NOW(),'system',NULL,NULL,'mampu menyusun informasi terkait produk dalam negeri dan informasi pasar negara tujuan seperti perilaku konsumen dan tren di negara tujuan',129),
    (NOW(),'system',NULL,NULL,'mampu menganalisis data dan informasi produk unggulan daerah/potensial ekspor dan pangsa pasar lokal/pasar tujuan ekspor serta mampu berkomunikasi secara efektif memberikan masukan dalam rangka perbaikan',129),
    (NOW(),'system',NULL,NULL,'mampu menyajikan data dan informasi terkait pengusaha/produsen/ekportir yang memenuhi standar untuk mengikuti kegiatan promosi perdagangan dan/ atau pemetaan produk unggulan daerah/potensial ekspor dan pangsa pasar lokal/pasar tujuan ekspor',129),
    (NOW(),'system',NULL,NULL,'mampu berkomunikasi secara efektif terkait kegiatan promosi perdagangan',129),
    (NOW(),'system',NULL,NULL,'mampu mempersiapkan pelaksanaan promosi perdagangan, meliputi pengecekan lokasi, sarana dan prasarana, seleksi dan penentuan peserta, serta mengkoordinasikan pelaksanaan promosi dengan pihak-pihak terkait',129),
    (NOW(),'system',NULL,NULL,'mampu berkomunikasi secara aktif menyusun laporan pelaksanaan kegiatan promosi perdagangan',129),
    (NOW(),'system',NULL,NULL,'mampu menganalisis data dan informasi transaksi hasil promosi perdagangan atau misi pembelian',129),
    (NOW(),'system',NULL,NULL,'mampu berkomunikasi secara efektif dalam rangka menyajikan data dan informasi perdagangan sesuai kewenangannya',130),
    (NOW(),'system',NULL,NULL,'mampu melakukan penyajian data dan informasi yang akan ditampulkan di website',130),
    (NOW(),'system',NULL,NULL,'mampu berkomunikasi secara efektif dalam memberikan informasi yang relevan kepada masyarakat dan stakeholder tentang data dan informasi perdagangan yang menjadi kewenangannya',130),
    (NOW(),'system',NULL,NULL,'Kemampuan menganalisis dampak dalam implementasi kebijakan FTA Bilateral dan MultiLateral',131),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan perhitungan alokasi ekspor dan impor untuk produk Bahan Baku/ Bahan penolong',131),
    (NOW(),'system',NULL,NULL,'Kemampuan menyusun perencanaan dan kemampuan melaksanakan program monitoring terhadap implementasi kebijakan pengelolaan ekspor/impor.',131),
    (NOW(),'system',NULL,NULL,'Kemampuan menyusun perencanaan dan kemampuan melaksanakan program monitoring terhadap implementasi kebijakan pengelolaan ekspor/impor.',131),
    (NOW(),'system',NULL,NULL,'mampu menganalisis faktor-faktor yang mempengaruhi kebijakan ekspor dan impor seperti selera konsumen, harga barang, nilai tukar dan biaya logistik',131),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan sinkronisasi data dan informasi serta menyusun bahan publikasi kiterkait ketentuan pengelolan ekspor/impor dan memetakan produk unggulan ekspor dengan metode komposit',131),
    (NOW(),'system',NULL,NULL,'kemampuan verifikasi dokumen administrasi,  identifikasi spesifikasi/kriteria Barang melalui',132),
    (NOW(),'system',NULL,NULL,'analisa kualitatif dan/atau kuantitatif',132),
    (NOW(),'system',NULL,NULL,'melakukan verifikasi di  Tempat Penimbunan Berikat (TPB) / Kawasan Perdagangan Bebas dan Pelabuhan Bebas (KPBPB) , Kawasan Ekonomi Khusus (KEK) terkait permohonan penerbitan perizinan atau non perizinan di bidang perdagangan.',132),
    (NOW(),'system',NULL,NULL,'Kemampuan mensosialisasikan kebijakan dan memberikan bimbingan, coaching mentoring kepada pihak-pihak terkait dalam melakukan analisis kelayakan penerbitan dokumen perizinan/non perizinan bidang perdagangan dengan metode komunikasi yang baik dan terstruktur',132),
    (NOW(),'system',NULL,NULL,'Kemampuan memecahkan masalah dengan metode analisis pemecahan SWOT',132),
    (NOW(),'system',NULL,NULL,'mampu melakukan pemantauan harga atau stok barang pokok dan barang penting sesuai dengan prosedur yang ditetapkan',133),
    (NOW(),'system',NULL,NULL,'mampu melakukan analisis secara kualitatif dan kuantitatif terkait  hasil Pemantauan Harga dan Pasokan/Stok Barang Kebutuhan Pokok dan Barang Penting',133),
    (NOW(),'system',NULL,NULL,'mampu melakukan analisis data dan informasi terkait jaringan distribusi, sarana perdagangan dan logistik dan potensi, kebutuhan dan perhitungan pembiayaan pembangunan/revitalisasi sarana perdagangan serta analisis pemberdayaan dan peningkatan kualitas pengelolaan pasar rakyat',133),
    (NOW(),'system',NULL,NULL,'mampu melakukan analisis potensi isu dan isu kenaikan/penurunan harga dan stok Barang Kebutuhan Pokok dan Barang Penting dan mampu melakukan analisis kenaikan dan penurunan harga komoditi secara ekstrim yang berdampak kepada inflasi/deflasi',133),
    (NOW(),'system',NULL,NULL,'mampu melakukan verifikasi langsung by sistem (SP2KP dan check & balance pelaku usaha terkait (produsen, distributor, pengecer)',133),
    (NOW(),'system',NULL,NULL,'Kemampuan mengkoordinir pelaksanaan kegiatan pemberdayaan konsumen dan pembinaan pelaku usaha, baik sosialisasi dan bimbingan teknis/workshop.',134),
    (NOW(),'system',NULL,NULL,'Kemampuan memonitor pelaksanaan kegiatan pemberdayaan konsumen dan pembinaan pelaku usaha, mengidentifikasi potensi masalah untuk menentukan tindakan antisipatif dan mengambil keputusan jika terjadi permasalahan di lapangan.',134),
    (NOW(),'system',NULL,NULL,'Kemampuan menyampaikan informasi dalam kegiatan pemberdayaan konsumen dan pembinaan pelaku usaha.',134),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan koordinasi dengan instansi/ lembaga terkait dan membuat laporan diseminasi pada kegiatan yang memenuhi hasil kerja minimal dalam rangka pemberdayaan konsumen dan pembinaan pelaku usaha.',134),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan survey pasar atau produk ekspor.',135),
    (NOW(),'system',NULL,NULL,'Kemampuan menganalisis kesesuaian antara pelaku usaha ekspor dengan peluang pasar ekspor.',135),
    (NOW(),'system',NULL,NULL,'Kemempauan melakukan Pemetaan atau identifikasi Produk Unggulan dan Potensial Daerah yang Berorientasi Ekspor.',135),
    (NOW(),'system',NULL,NULL,'Kemampuan mengidentifikasi standar dan kriteria peserta promosi.',135),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan pendampingan penyelenggaraan promosi perdagangan.',135),
    (NOW(),'system',NULL,NULL,'Kemampuan melakukan identifikasi dan solusi  permasalahan terkait pameran dagang atau produk unggulan daerah.',135),
    (NOW(),'system',NULL,NULL,'Kemampuan menyusun rencana dan melaksanakan program monitoring terhadap implementasi Pengelolaan sistem informasi perdagangan yang menjadi kewenangannya.',136),
    (NOW(),'system',NULL,NULL,'Kemampuan mengidentifikasi kekurangan dan merumuskan perbaikan terhadap  implementasi Pengelolaan sistem informasi perdagangan yang menjadi kewenangannya.',136),
    (NOW(),'system',NULL,NULL,'Kemampuan memberikan bimbingan dan fasilitasi kepada instansi lain atau stakeholder terkait dalam menerapkan Sistem Informasi Perdagangan.',136),
    (NOW(),'system',NULL,NULL,'mampu melakukan penyelarasan (harmonisasi) dengan peraturan perundang-undangan yang lain dan melakukan uji publik dalam rangka perumusan kebijakan pengelolaan ekspor impor.',137),
    (NOW(),'system',NULL,NULL,'mampu merumuskan rekomendasi strategis dalam pengelolaan ekspor dan impor.',137),
    (NOW(),'system',NULL,NULL,'mampu melakukan kaji ulang dan penghitungan harga patokan ekspor (HPE).',137),
    (NOW(),'system',NULL,NULL,'mampu merumuskan solusi terhadap hambatan dalam implementasi suatu kebijakan dan mengambil keputusan untuk meningkatkan efektivitas perumusan suatu kebijakan pengelolaan ekspor/impor.',137),
    (NOW(),'system',NULL,NULL,'mampu menetapkan upaya perbaikan dan menetapkan langkah-langkah tindak lanjut dari hasil monitoring dan evaluasi pelaksanaan kegiatan pengelolaan ekspor/impor.',137),
    (NOW(),'system',NULL,NULL,'mampu melakukan validasi data dan legalitas dokumen permohonan penerbitan dokumen perizinan/non perizinan bidang perdagangan.',138),
    (NOW(),'system',NULL,NULL,'mampu melakukan pemantauan hasil penerbitan dokumen perizinan/non perizinan bidang perdagangan.',138),
    (NOW(),'system',NULL,NULL,'mampu melakukan evaluasi terhadap teknik/metode/sistem cara kerja, melakukan pengembangan atau perbaikan cara kerja analisis kelayakan penerbitan dokumen perizinan/non perizinan bidang perdagangan.',138),
    (NOW(),'system',NULL,NULL,'mampu menyusun pedoman, petunjuk teknis, cara kerja yang dijadikan norma, standar, prosedur, instrumen pelaksanaan analisis kelayakan penerbitan dokumen perizinan/non perizinan bidang perdagangan.',138),
    (NOW(),'system',NULL,NULL,'mampu menyakinkan dan memperoleh dukungan dari stakeholder  pelaksanaan  analisis kelayakan penerbitan dokumen perizinan/non perizinan bidang perdagangan  dan memberikan bimbingan dan fasilitas kepada instansi lain atau stakeholder terkait.',138),
    (NOW(),'system',NULL,NULL,'mampu menentukan kriteria dan merekomendasikan kegiatan stabilisasi harga barang pokok dan barang penting di daerah.',139),
    (NOW(),'system',NULL,NULL,'mampu membuat kajian early warning terkait kondisi perkembangan harga dan stok atau pasokan barang kebutuhan pokok dan barang penting.',139),
    (NOW(),'system',NULL,NULL,'mampu merekomendasikan harga eceran tertinggi barang pokok dan barang penting dan harga acuan berdasarkan hasil analisis laporan hasil pemantauan harga dan ketersediaan barang pokok dan barang penting.',139),
    (NOW(),'system',NULL,NULL,'mampu memverifikasi proposal pembangunan atau revitalisasi dan pemberian bantuan sarana perdagangan.',139),
    (NOW(),'system',NULL,NULL,'mampu melakukan kajian potensi kerjasama pengembangan perdagangan dalam negeri dengan pihak-pihak terkait.',139),
    (NOW(),'system',NULL,NULL,'mampu melakukan evaluasi terhadap pelaksanaan kebijakan pemberdayaan konsumen dalam rangka menentukan penyempurnaan pelaksanaan kegiatan ke depan.',140),
    (NOW(),'system',NULL,NULL,'mampu memetakan kekuatan sumber daya dalam rangka kelancaran pelaksanaan tugas di bidang pemberdayaan konsumen dan pembinaan pelaku usaha.',140),
    (NOW(),'system',NULL,NULL,'mampu menjalin kerjasama antar instansi di dalam negeri/ antar negara terkait pelaksanaan kegiatan pemberdayaan konsumen dan pembinaan pelaku usaha.',140),
    (NOW(),'system',NULL,NULL,'mampu melaksanakan Misi Dagang Produk Ekspor Unggulan ke negara mitra dan konsultasi bisnis pelaku usaha.',141),
    (NOW(),'system',NULL,NULL,'mampu melakukan seleksi dan penentuan peserta atau produk yang memenuhi standar untuk mengikuti kegiatan promosi perdagangan.',141),
    (NOW(),'system',NULL,NULL,'mampu menentukan target transaksi pelaksanaan promosi perdagangan dan melakukan pemantauan transaksi hasil promosi perdagangan atau misi pembelian.',141),
    (NOW(),'system',NULL,NULL,'mampu menyusun rekomendasi rujukan negara tujuan promosi perdagangan dan metode penetrasi pasar.',141),
    (NOW(),'system',NULL,NULL,'mampu melakukan kajian potensi kerjasama dengan mitra kerjasama dalam dan luar negeri dan menyusun naskah kerja sama pengembangan ekspor.',141),
    (NOW(),'system',NULL,NULL,'Mampu melakukan validasi administratif atas permohonan penyelidikan anti dumping/anti subsidi/Pengamanan Perdagangan.',142),
    (NOW(),'system',NULL,NULL,'Mampu melakukan identifikasi data dan informasi dalam pra penyelidikan, pelaksanaan penyelidikan dan paska penyelidikan anti dumping/anti subsidi/pengamanan perdagangan.',142),
    (NOW(),'system',NULL,NULL,'Mampu menyusun surat pemberitahuan kepada pihak terkait dalam bahasa Indonesia dan asing.',142),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis data dan informasi dokumen inisiasi/ petisi penyelidikan.',143),
    (NOW(),'system',NULL,NULL,'Mampu menyajikan data dan informasi terkait penanganan masalah hambatan perdagangan.',143),
    (NOW(),'system',NULL,NULL,'Mampu memberikan informasi kepada pemangku kepentingan terkait penanganan masalah hambatan perdagangan.',143),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pemutakhiran informasi perkembangan masalah hambatan perdagangan.',143),
    (NOW(),'system',NULL,NULL,'Mampu menyusun laporan berkala perkembangan penanganan masalah hambatan perdagangan.',143),
    (NOW(),'system',NULL,NULL,'Mampu menyusun konsep siaran pers terkait penanganan masalah hambatan perdagangan.',143),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi bukti pendukung terkait pelaksanaan penanganan sengketa perdagangan internasional.',144),
    (NOW(),'system',NULL,NULL,'Mampu menyusun rencana kerja penanganan sengketa perdagangan internasional.',144),
    (NOW(),'system',NULL,NULL,'Mampu melakukan analisis sederhana terhadap permintaan konsultasi, pembentukan panel, pemberitahuan banding, panel kepatuhan, maupun arbitrase lainnya.',144),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi jawaban atas pertanyaan yang diajukan oleh badan penyelesaian sengketa perdagangan internasional.',144),
    (NOW(),'system',NULL,NULL,'Mampu menyusun laporan berkala terkait perkembangan penanganan sengketa perdagangan internasional.',144),
    (NOW(),'system',NULL,NULL,'Mampu mengklasifikasikan posisi dasar atau kepentingan politik dan hubungan luar negeri terkait substansi bidang perdagangan di kawasan atau negara mitra dagang yang ditangani.',145),
    (NOW(),'system',NULL,NULL,'Mampu memonitor dan menentukan potensi dan tantangan terkait substansi bidang perdagangan di kawasan atau negara mitra dagang yang ditangani terhadap kepentingan ekonomi dan hubungan luar negeri.',145),
    (NOW(),'system',NULL,NULL,'Mampu mengolah data dan informasi menjadi materi untuk ditelaah.',145),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi, mengumpulkan, mengolah dan menyiapkan bahan bahan yang dibutuhkan dalam rangka pendampingan hukum perdagangan internasional.',146),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi data dan informasi terkait permasalahan yang muncul dalam rangka pendampingan hukum bagi perjanjian perdagangan internasional.',146),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi bukti pendukung terkait pendampingan hukum dalam perjanjian perdagangan internasional.',146),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis term of reference atau scopingpaper terkait perundingan/evaluasi perjanjian perdagangan internasional.',146),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis dokumen terkait perjanjian perdagangan internasional.',146),
    (NOW(),'system',NULL,NULL,'Mampu menyusun rencana pelaksanaan kegiatan advokasi kebijakan, melalui persuasi, sosialisasi, bimbingan teknis, pendampingan, monitoring evaluasi advokasi kebijakan publik.',147),
    (NOW(),'system',NULL,NULL,'Mampu melakukan sosialisasi kebijakan publik dengan presentasi yang efektif, mengunakan fitur dan alat bantu presentasi, sesuai tipe audiens serta strategi penyampaian pesan yang adekuat kepada para stakeholder sehingga dapat memahami serta menerapkan kebijakan.',147),
    (NOW(),'system',NULL,NULL,'Mampu mengidentifikasi mana kebutuhan meeting, memformulasikan agenda meeting dan mendesain merancang materi dan bahan, alat bantu, run down meeting serta minutes of meeting yang efektif.',147),
    (NOW(),'system',NULL,NULL,'Mampu melakukan kegiatan asistensi terkait permohonan tindakan anti dumping/imbalan/tindakan pengamanan perdagangan.',148),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis data dan informasi terkait penyelidikan anti-dumping, subsidi dan tindakan pengamanan.',148),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis tanggapan/ submisi atas laporan sementara pengenaan BMADS/BMIS/BMTP.',148),
    (NOW(),'system',NULL,NULL,'Mampu memberikan advise/masukan substantif terkait pelaksanaan penyelidikan.',148),
    (NOW(),'system',NULL,NULL,'Mampu menganalisis permasalahan dan kebijakan dari negara mitra dagang yang berpotensi menghambat perdagangan.',149),
    (NOW(),'system',NULL,NULL,'Mampu menyusun bahan koordinasi dalam rangka penanganan masalah hambatan perdagangan.',149),
    (NOW(),'system',NULL,NULL,'Mampu menyusun butir wicara (oral statement untuk pelaksanaan sidang (hearing/ konsultasi/ kegiatan verifikasi dengan otoritas negara mitra dagang.',149),
    (NOW(),'system',NULL,NULL,'Mampu melakukan advokasi kepada perusahaan yang terdampak dari masalah hambatan perdagangan.',149),
    (NOW(),'system',NULL,NULL,'Mampu melakukan analisis dampak terhadap kinerja ekspor pasca penanganan masalah hambatan perdagangan.',149),
    (NOW(),'system',NULL,NULL,'Mampu melakukan analisis terhadap permasalahan hukum yang terkait dengan permintaan konsultasi, pembentukan panel, pemberitahuan banding, panel kepatuhan, maupun arbitrase lainnya.',150),
    (NOW(),'system',NULL,NULL,'Mampu melakukan analisis terhadap penanganan sengketa perdagangan internasional dalam bentuk putusan awal (preliminary ruling) danlaporan sementara (interim report).',150),
    (NOW(),'system',NULL,NULL,'Mampu menyusun jawaban/ tanggapan atas permintaan konsultasi, pembentukan panel, pemberitahuan banding, panel kepatuhan, maupun arbitrase lainnya.',150),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pendampingan hukum pada kegiatan konsultasi/ Panel Hearing/ Apellate Body (AB) Hearing/ Compliance Panel Hearing/ Arbitrase lainnya.',150),
    (NOW(),'system',NULL,NULL,'Mampu melakukan kajian atas permasalahan hukum yang terkait dengan penanganan sengketa perdagangan internasional dalam rangka memberikan rekomendasi Langkah langkah tindak lanjut kepada pihak yang berwenang.',150),
    (NOW(),'system',NULL,NULL,'Mampu menelaah materi dengan mengkorelasikan hubungan sebab akibat.',151),
    (NOW(),'system',NULL,NULL,'Mampu merumuskan hasil korelasi secara logis dengan mempertimbangkan faktor pro dan kontra serta kekuatan dan kelemahan suatu argumentasi.',151),
    (NOW(),'system',NULL,NULL,'Mampu menganalisisarah dan strategi kebijakan luar negeri Indonesia pada substansi bidang perdagangan di kawasan atau negara mitra dagang yang ditangani.',151),
    (NOW(),'system',NULL,NULL,'Mampu melakukan analisis terhadap permasalahan hukum terkait perjanjian perdagangan internasional.',152),
    (NOW(),'system',NULL,NULL,'Mampu melakukan kajian hukum (legal scrubbing) atas teks hukum dalam rangka perjanjian perdagangan internasional.',152),
    (NOW(),'system',NULL,NULL,'Mampu memberikan pendampingan hukum pada pertemuan/ sidang/konferensi terkait perjanjian perdagangan internasional.',152),
    (NOW(),'system',NULL,NULL,'Mampu melakukan kajian atas permasalahan hukum yang terkait dengan perjanjian perdagangan internasional dalam rangka memberikan rekomendasi lebih lanjut kepada pihak yang berwenang.',152),
    (NOW(),'system',NULL,NULL,'Mampu mengembangkan serta menjalankan strategi atau intervensi dalam mengatasi hambatan sistemik dan resistensi stakeholder dalam menerapkan kebijakan, serta mampu mengembangkan serta menjalankan strategi atau intervensi dalam memaksimalkan sumber daya yang dimiliki stakeholder.',153),
    (NOW(),'system',NULL,NULL,'Mampu mengimplementasikan strategi komunikasi dengan target dan waktu yang terukur dan terencana dengan mendapatkan hasil sesuai yang diharapkan.',153),
    (NOW(),'system',NULL,NULL,'Mampu mengantarkan sebuah sesi presentasi yang efektif dan efisien dengan menggunakan alat bantu dan strategi presentasi yang cukup sehingga pesan dapat tersampaikan dengan baik ke audien, mampu mengendalikan diri dalam berurusan dengan kondisi dan audiens yang sulit dan mampu menguasai jalannya sesi presentasi sesuai dengan alokasi materi dan waktu yang telah ditetapkan.',153),
    (NOW(),'system',NULL,NULL,'Mampu mengkontrol jalannya meeting dengan efektif dan efisien sesuai dengan sasaran dengan menjalankan strategi yang telah ditetapkan sebelumnya, menggunakan alat bantu yang disediakan, serta sesuai dengan run down acara, mampu mengendalikan meeting dalam kondisi yang sulit dan mengatasi peserta rapat yang tidak koordinatif dan mampu untuk mengarahkan dan mencapai kata sepakat antar anggota meeting.',153),
    (NOW(),'system',NULL,NULL,'Mampu memberi masukan posisi Indonesia pada forum komite WTO dan forum internasional lainnya.',154),
    (NOW(),'system',NULL,NULL,'Mampu menyusun notifikasi penyelidikan.',154),
    (NOW(),'system',NULL,NULL,'Mampu membuat surat rekomendasi kebijakan terkait pengenaan tindakan BMAD/BMI/BMTP.',154),
    (NOW(),'system',NULL,NULL,'Mampu memimpin pelaksanaan tugas penyelidikan anti dumping, subsidi dan tindakan pengamanan.',154),
    (NOW(),'system',NULL,NULL,'Mampu merancang strategi penanganan masalah hambatan perdagangan ekspor.',155),
    (NOW(),'system',NULL,NULL,'Mampu melakukan pendampingan terhadap perusahaan pada kegiatan verifikasi dalam rangka penanganan masalah hambatan perdagangan.',155),
    (NOW(),'system',NULL,NULL,'Mampu melakukan monitoring dan evaluasi pada pemangku kepentingan terkait penanganan masalah hambatan perdagangan.',155),
    (NOW(),'system',NULL,NULL,'Mampu menyusun laporan hasil monitoring dan evaluasi penanganan masalah hambatan perdagangan.',155),
    (NOW(),'system',NULL,NULL,'Mampu mengevaluasi pelaksanaan penanganan sengketa perdagangan internasional dalam rangka mengantisipasi dampak hukum yang ditimbulkan terkait penanganan sengketa perdagangan internasional.',156),
    (NOW(),'system',NULL,NULL,'Mampu menyusun written submission maupun oral statement dalam rangka penanganan sengketa perdagangan internasional.',156),
    (NOW(),'system',NULL,NULL,'Mampu menyusun opini hukum terkait penyelesaian sengketa perdagangan internasional.',156),
    (NOW(),'system',NULL,NULL,'Mampu menyusun rekomendasi terkait penanganan sengketa perdagangan internasional.',156),
    (NOW(),'system',NULL,NULL,'Mampu memberikan pertimbangan hubungan sebab akibat yang lebih kompleks dalam merumuskan materi terkait substansi bidang perdagangan di kawasan atau negara mitra dagang yang ditangani.',157),
    (NOW(),'system',NULL,NULL,'Mampu menyertakan dan memperjelas sudut pandang yang berbeda untuk memperkaya hasil análisis.',157),
    (NOW(),'system',NULL,NULL,'Mampu merumuskan hasil observasi, isu dan ide yang kompleks menjadi hasil analisis yang mudah dimengerti.',157),
    (NOW(),'system',NULL,NULL,'Mampu melakukan analisis dampak hukum terkait perjanjian perdagangan internasional.',158),
    (NOW(),'system',NULL,NULL,'Mampu menyusun opini hukum terkait perumusan legal text dan non legal text serta menyusun opini hukum terkait implementasi dan kesesuaian kebijakan kementerian/lembaga dalam bidang perdagangan internasional.',158),
    (NOW(),'system',NULL,NULL,'Mampu menyusun analisis hukum terkait ratifikasi perjanjian internasional berdasarkan hasil rapat dengar pendapat di berbagai forum.',158),
    (NOW(),'system',NULL,NULL,'Mampu menyusun rekomendasi terkait perjanjian perdagangan internasional dan memberikan pendampingan hukum dalam rangka perundingan perdagangan internasional.',158),
    (NOW(),'system',NULL,NULL,'Mampu memberdayakan stakeholder untuk mengembangkan strategi advokasi yang tepat untuk diri mereka sendiri,mengidentifikasi hambatan di lingkungan mereka sendiri dalam penerapan kebijakan serta menemukan akses ke sumber daya yang dibutuhkan untuk menerapkan kebijakan.',159),
    (NOW(),'system',NULL,NULL,'Mampu mengevaluasi strategi komunikasi yang telah dilaksanakan dan menyusun strategi baru yang lebih efektif dalam rangka meningkatkan kualitas komunikasi atau mencapai target-target yang lebih tinggi atau menghadapi situasi yang lebih sulit.',159),
    (NOW(),'system',NULL,NULL,'Mampu mengevaluasi diri sendiri dan orang lain dalam menjalankan suatu sesi presentasi dan menyediakan masukan berdasarkan hasil evaluasi tersebut dan menjadi tutor yang baik dalam membimbing orang lain menguasai teknik presentasi yang efektif dan efisien.',159),
    (NOW(),'system',NULL,NULL,'Mampu untuk mengevaluasi jalannya suatu meeting serta menyusun suatu strategi serta intervensi untuk mengoptimalkan meeting selanjutnya.',159);