<?php

namespace Database\Seeders\Maintenance;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnitKerjaSeeder extends Seeder
{
    public function run()
    {
        // DB::table('tbl_unit_kerja')->insert([
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Biro Perencanaan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Biro Organisasi dan Sumber Daya Manusia",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Biro Keuangan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Biro Hukum",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Biro Umum dan Layanan Pengadaan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Biro Hubungan Masyarakat",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Biro Advokasi Perdagangan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Pusat Penanganan Isu Strategis",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Pusat Pendidikan dan Pelatihan Aparatur Perdagangan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Pusat Pembinaan Jabatan Fungsional Perdagangan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Pusat Pelatihan Sumber Daya Manusia Ekspor dan Jasa Perdagangan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Pusat Data dan Sistem Informasi",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Sekretariat Direktorat Jenderal Perdagangan Dalam Negeri",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Bina Usaha Perdagangan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Sarana Perdagangan dan Logistik",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Barang Kebutuhan Pokok dan Barang Penting",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Penggunaan dan Pemasaran Produk Dalam Negeri",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Perdagangan Melalui Sistem Elektronik dan Perdagangan Jasa",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Sekretariat Direktorat Jenderal Perlindungan Konsumen dan Tertib Niaga",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Pemberdayaan Konsumen",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Standardisasi Dan Pengendalian Mutu",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Metrologi",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Pengawasan Barang Beredar Dan Jasa",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Tertib Niaga",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Sekretariat Direktorat Jenderal Perdagangan Luar Negeri",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Ekspor Produk Pertanian Dan Kehutanan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Ekspor Produk Industri Dan Pertambangan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Impor",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Fasilitasi Ekspor Dan Impor",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Pengamanan Perdagangan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Sekretariat Direktorat Jenderal Perundingan Perdagangan Internasional",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Perundingan Organisasi Perdagangan Dunia",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Perundingan ASEAN",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Perundingan Antar Kawasan dan Organisasi Internasional",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Perundingan Bilateral",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Perundingan Perdagangan Jasa",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Sekretariat Direktorat Jenderal Pengembangan Ekspor Nasional",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Pengembangan Pasar Dan Informasi Ekspor",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Pengembangan Ekspor Produk Manufaktur",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Pengembangan Ekspor Jasa dan Produk Kreatif",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Direktorat Pengembangan Ekspor Produk Primer",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Sekretariat Inspektorat Jenderal",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Inspektorat I",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Inspektorat II",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Inspektorat III",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Inspektorat IV",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Inspektorat IV",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Inspektorat IV",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Inspektorat IV",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Inspektorat IV",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Sekretariat Badan Pengawas Perdagangan Berjangka Komoditi",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Biro Peraturan Perundang-undangan dan Penindakan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Biro Pengawasan Perdagangan Berjangka Komoditi, Sistem Resi Gudang, dan Pasar Lelang Komoditas ",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Biro Pembinaan dan Pengembangan Perdagangan Berjangka Komoditi",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Sekretariat Badan Kebijakan Perdagangan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Pusat Kebijakan Perdagangan Domestik",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Pusat Kebijakan Perdagangan Internasional",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        //     [
        //         "created_at" => now(),
        //         "created_by" => "system",
        //         "operasional" => "KEMENTERIAN",
        //         "name" => "Pusat Kebijakan Ekspor Impor dan Pengamanan Perdagangan",
        //         "tipe_instansi_code" => "kementerian_lembaga",
        //     ],
        // ]);
    }
}
