<?php

namespace Database\Seeders\Security;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoleMenuSeeder extends Seeder
{
    public function run()
    {
        DB::table('tbl_role_menu')->insert([
            ['role_code' => 'super_admin', 'menu_code' => 'DAS_1', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'USR_1', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'USR_2', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'USR_3', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'USR_4', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'MNT_1', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'MNT_2', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'MNT_3', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'MNT_4', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'MNT_5', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'MNT_6', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'MNT_7', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'MNT_8', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'MNT_9', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'SEC_1', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'SEC_2', 'created_by' => "system"],
            ['role_code' => 'super_admin', 'menu_code' => 'SEC_3', 'created_by' => "system"],

            ['role_code' => 'admin_formasi', 'menu_code' => 'DAS_1', 'created_by' => "system"],
            ['role_code' => 'admin_formasi', 'menu_code' => 'FOR_1', 'created_by' => "system"],
            ['role_code' => 'admin_formasi', 'menu_code' => 'FOR_8', 'created_by' => "system"],
            ['role_code' => 'admin_formasi', 'menu_code' => 'FOR_11', 'created_by' => "system"],
            ['role_code' => 'admin_formasi', 'menu_code' => 'FOR_12', 'created_by' => "system"],
            ['role_code' => 'admin_formasi', 'menu_code' => 'MNT_1', 'created_by' => "system"],
            ['role_code' => 'admin_formasi', 'menu_code' => 'MNT_2', 'created_by' => "system"],
            ['role_code' => 'admin_formasi', 'menu_code' => 'MNT_3', 'created_by' => "system"],
            ['role_code' => 'admin_formasi', 'menu_code' => 'MNT_4', 'created_by' => "system"],
            ['role_code' => 'admin_formasi', 'menu_code' => 'MNT_5', 'created_by' => "system"],
            ['role_code' => 'admin_formasi', 'menu_code' => 'MNT_6', 'created_by' => "system"],

            ['role_code' => 'admin_ukom', 'menu_code' => 'DAS_1', 'created_by' => "system"],
            ['role_code' => 'admin_ukom', 'menu_code' => 'UKM_1', 'created_by' => "system"],
            ['role_code' => 'admin_ukom', 'menu_code' => 'MNT_1', 'created_by' => "system"],
            ['role_code' => 'admin_ukom', 'menu_code' => 'MNT_2', 'created_by' => "system"],
            ['role_code' => 'admin_ukom', 'menu_code' => 'MNT_3', 'created_by' => "system"],
            ['role_code' => 'admin_ukom', 'menu_code' => 'MNT_4', 'created_by' => "system"],
            ['role_code' => 'admin_ukom', 'menu_code' => 'MNT_5', 'created_by' => "system"],
            ['role_code' => 'admin_ukom', 'menu_code' => 'MNT_6', 'created_by' => "system"],
            ['role_code' => 'admin_ukom', 'menu_code' => 'UKM_1', 'created_by' => "system"],
            ['role_code' => 'admin_ukom', 'menu_code' => 'UKM_2', 'created_by' => "system"],
            ['role_code' => 'admin_ukom', 'menu_code' => 'UKM_3', 'created_by' => "system"],
            ['role_code' => 'admin_ukom', 'menu_code' => 'UKM_4', 'created_by' => "system"],

            ['role_code' => 'admin_pak', 'menu_code' => 'DAS_1', 'created_by' => "system"],
            ['role_code' => 'admin_pak', 'menu_code' => 'PAK_1', 'created_by' => "system"],
            ['role_code' => 'admin_pak', 'menu_code' => 'MNT_1', 'created_by' => "system"],
            ['role_code' => 'admin_pak', 'menu_code' => 'MNT_2', 'created_by' => "system"],
            ['role_code' => 'admin_pak', 'menu_code' => 'MNT_3', 'created_by' => "system"],
            ['role_code' => 'admin_pak', 'menu_code' => 'MNT_4', 'created_by' => "system"],
            ['role_code' => 'admin_pak', 'menu_code' => 'MNT_5', 'created_by' => "system"],
            ['role_code' => 'admin_pak', 'menu_code' => 'MNT_6', 'created_by' => "system"],

            ['role_code' => 'admin_akp', 'menu_code' => 'DAS_1', 'created_by' => "system"],
            ['role_code' => 'admin_akp', 'menu_code' => 'USR_1', 'created_by' => "system"],
            ['role_code' => 'admin_akp', 'menu_code' => 'USR_4', 'created_by' => "system"],
            ['role_code' => 'admin_akp', 'menu_code' => 'AKP_1', 'created_by' => "system"],
            ['role_code' => 'admin_akp', 'menu_code' => 'AKP_3', 'created_by' => "system"],
            ['role_code' => 'admin_akp', 'menu_code' => 'AKP_4', 'created_by' => "system"],
            ['role_code' => 'admin_akp', 'menu_code' => 'AKP_5', 'created_by' => "system"],
            ['role_code' => 'admin_akp', 'menu_code' => 'MNT_1', 'created_by' => "system"],
            ['role_code' => 'admin_akp', 'menu_code' => 'MNT_2', 'created_by' => "system"],
            ['role_code' => 'admin_akp', 'menu_code' => 'MNT_3', 'created_by' => "system"],
            ['role_code' => 'admin_akp', 'menu_code' => 'MNT_4', 'created_by' => "system"],
            ['role_code' => 'admin_akp', 'menu_code' => 'MNT_5', 'created_by' => "system"],
            ['role_code' => 'admin_akp', 'menu_code' => 'MNT_6', 'created_by' => "system"],
            // ['role_code' => 'admin_instansi', 'menu_code' => 'DAS_1', 'created_by' => "system"],

            ['role_code' => 'pusbin', 'menu_code' => 'DAS_1', 'created_by' => "system"],
            ['role_code' => 'pusbin', 'menu_code' => 'USR_1', 'created_by' => "system"],
            ['role_code' => 'pusbin', 'menu_code' => 'USR_2', 'created_by' => "system"],
            ['role_code' => 'pusbin', 'menu_code' => 'USR_3', 'created_by' => "system"],
            ['role_code' => 'pusbin', 'menu_code' => 'MNT_1', 'created_by' => "system"],
            ['role_code' => 'pusbin', 'menu_code' => 'MNT_2', 'created_by' => "system"],
            ['role_code' => 'pusbin', 'menu_code' => 'MNT_3', 'created_by' => "system"],
            ['role_code' => 'pusbin', 'menu_code' => 'MNT_4', 'created_by' => "system"],
            ['role_code' => 'pusbin', 'menu_code' => 'MNT_5', 'created_by' => "system"],
            ['role_code' => 'pusbin', 'menu_code' => 'MNT_6', 'created_by' => "system"],

            ['role_code' => 'unit_pembina', 'menu_code' => 'DAS_1', 'created_by' => "system"],
            ['role_code' => 'unit_pembina', 'menu_code' => 'USR_1', 'created_by' => "system"],
            ['role_code' => 'unit_pembina', 'menu_code' => 'USR_2', 'created_by' => "system"],
            ['role_code' => 'unit_pembina', 'menu_code' => 'USR_3', 'created_by' => "system"],
            ['role_code' => 'unit_pembina', 'menu_code' => 'MNT_1', 'created_by' => "system"],
            ['role_code' => 'unit_pembina', 'menu_code' => 'MNT_2', 'created_by' => "system"],
            ['role_code' => 'unit_pembina', 'menu_code' => 'MNT_3', 'created_by' => "system"],
            ['role_code' => 'unit_pembina', 'menu_code' => 'MNT_4', 'created_by' => "system"],
            ['role_code' => 'unit_pembina', 'menu_code' => 'MNT_5', 'created_by' => "system"],
            ['role_code' => 'unit_pembina', 'menu_code' => 'MNT_6', 'created_by' => "system"],

            ['role_code' => 'bkpsdm_bkd', 'menu_code' => 'DAS_1', 'created_by' => "system"],
            ['role_code' => 'bkpsdm_bkd', 'menu_code' => 'USR_1', 'created_by' => "system"],
            ['role_code' => 'bkpsdm_bkd', 'menu_code' => 'USR_2', 'created_by' => "system"],
            ['role_code' => 'bkpsdm_bkd', 'menu_code' => 'USR_3', 'created_by' => "system"],
            ['role_code' => 'bkpsdm_bkd', 'menu_code' => 'MNT_1', 'created_by' => "system"],
            ['role_code' => 'bkpsdm_bkd', 'menu_code' => 'MNT_2', 'created_by' => "system"],
            ['role_code' => 'bkpsdm_bkd', 'menu_code' => 'MNT_3', 'created_by' => "system"],
            ['role_code' => 'bkpsdm_bkd', 'menu_code' => 'MNT_4', 'created_by' => "system"],
            ['role_code' => 'bkpsdm_bkd', 'menu_code' => 'MNT_5', 'created_by' => "system"],
            ['role_code' => 'bkpsdm_bkd', 'menu_code' => 'MNT_6', 'created_by' => "system"],
            // ['role_code' => 'pengatur_siap', 'menu_code' => 'DAS_1', 'created_by' => "system"],

            ['role_code' => 'ses', 'menu_code' => 'DAS_1', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'USR_1', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'USR_4', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'FOR_1', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'FOR_2', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'FOR_3', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'FOR_4', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'FOR_5', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'FOR_6', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'FOR_7', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'FOR_9', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'MNT_1', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'MNT_2', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'MNT_3', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'MNT_4', 'created_by' => "system"],
            ['role_code' => 'ses', 'menu_code' => 'MNT_5', 'created_by' => "system"],

            ['role_code' => 'unit_kerja', 'menu_code' => 'DAS_1', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'USR_1', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'USR_4', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'FOR_1', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'FOR_2', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'FOR_3', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'FOR_4', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'FOR_5', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'FOR_6', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'FOR_7', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'FOR_9', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'MNT_1', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'MNT_2', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'MNT_3', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'MNT_4', 'created_by' => "system"],
            ['role_code' => 'unit_kerja', 'menu_code' => 'MNT_5', 'created_by' => "system"],

            ['role_code' => 'opd', 'menu_code' => 'DAS_1', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'USR_1', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'USR_4', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'FOR_1', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'FOR_2', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'FOR_3', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'FOR_4', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'FOR_5', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'FOR_6', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'FOR_7', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'FOR_9', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'MNT_1', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'MNT_2', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'MNT_3', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'MNT_4', 'created_by' => "system"],
            ['role_code' => 'opd', 'menu_code' => 'MNT_5', 'created_by' => "system"],

            ['role_code' => 'user_external', 'menu_code' => 'DAS_1', 'created_by' => "system"],
            ['role_code' => 'user_external', 'menu_code' => 'AKP_1', 'created_by' => "system"],
            ['role_code' => 'user_external', 'menu_code' => 'AKP_2', 'created_by' => "system"],
            ['role_code' => 'user_external', 'menu_code' => 'UKM_1', 'created_by' => "system"],
            ['role_code' => 'user_external', 'menu_code' => 'UKM_3', 'created_by' => "system"],
            ['role_code' => 'user_external', 'menu_code' => 'FOR_1', 'created_by' => "system"],
            ['role_code' => 'user_external', 'menu_code' => 'FOR_10', 'created_by' => "system"],
        ]);
    }
}
